/*
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.ui.tests;

import co.edu.unal.dsl.AppPrecio.ui.internal.AppPrecioActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AppPrecioUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AppPrecioActivator.getInstance().getInjector("co.edu.unal.dsl.AppPrecio");
	}

}
