/*
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAppPrecioScopeProvider extends DelegatingScopeProvider {
}
