/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio.impl;

import co.edu.unal.dsl.appPrecio.AppPrecio;
import co.edu.unal.dsl.appPrecio.AppPrecioFactory;
import co.edu.unal.dsl.appPrecio.AppPrecioPackage;
import co.edu.unal.dsl.appPrecio.Arquitectura;
import co.edu.unal.dsl.appPrecio.Arreglo;
import co.edu.unal.dsl.appPrecio.Boton;
import co.edu.unal.dsl.appPrecio.BotonOpcionItem;
import co.edu.unal.dsl.appPrecio.CampoEntrada;
import co.edu.unal.dsl.appPrecio.Color;
import co.edu.unal.dsl.appPrecio.Componente;
import co.edu.unal.dsl.appPrecio.Dominio;
import co.edu.unal.dsl.appPrecio.Entidad;
import co.edu.unal.dsl.appPrecio.Evento;
import co.edu.unal.dsl.appPrecio.Interfaz;
import co.edu.unal.dsl.appPrecio.LLave;
import co.edu.unal.dsl.appPrecio.Lista;
import co.edu.unal.dsl.appPrecio.Listado;
import co.edu.unal.dsl.appPrecio.MetodoComponente;
import co.edu.unal.dsl.appPrecio.MetodoServicio;
import co.edu.unal.dsl.appPrecio.MetodoTecnologia;
import co.edu.unal.dsl.appPrecio.Propiedad;
import co.edu.unal.dsl.appPrecio.Servicio;
import co.edu.unal.dsl.appPrecio.Tecnologia;
import co.edu.unal.dsl.appPrecio.TipoDato;
import co.edu.unal.dsl.appPrecio.Tipos;
import co.edu.unal.dsl.appPrecio.TiposArregloListado;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AppPrecioPackageImpl extends EPackageImpl implements AppPrecioPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass appPrecioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dominioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arquitecturaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tecnologiaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass servicioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metodoComponenteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metodoServicioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metodoTecnologiaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entidadEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass interfazEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass propiedadEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass componenteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass campoEntradaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass botonEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass botonOpcionItemEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass listaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tiposEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lLaveEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arregloEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass listadoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tiposArregloListadoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum eventoEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum tipoDatoEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum colorEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private AppPrecioPackageImpl()
  {
    super(eNS_URI, AppPrecioFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link AppPrecioPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static AppPrecioPackage init()
  {
    if (isInited) return (AppPrecioPackage)EPackage.Registry.INSTANCE.getEPackage(AppPrecioPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredAppPrecioPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    AppPrecioPackageImpl theAppPrecioPackage = registeredAppPrecioPackage instanceof AppPrecioPackageImpl ? (AppPrecioPackageImpl)registeredAppPrecioPackage : new AppPrecioPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theAppPrecioPackage.createPackageContents();

    // Initialize created meta-data
    theAppPrecioPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theAppPrecioPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(AppPrecioPackage.eNS_URI, theAppPrecioPackage);
    return theAppPrecioPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAppPrecio()
  {
    return appPrecioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAppPrecio_Dominio()
  {
    return (EReference)appPrecioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAppPrecio_Arquitectura()
  {
    return (EReference)appPrecioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAppPrecio_Tecnologia()
  {
    return (EReference)appPrecioEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDominio()
  {
    return dominioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDominio_Servicios()
  {
    return (EReference)dominioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDominio_Entidades()
  {
    return (EReference)dominioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArquitectura()
  {
    return arquitecturaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArquitectura_Componentes()
  {
    return (EReference)arquitecturaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTecnologia()
  {
    return tecnologiaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTecnologia_Name()
  {
    return (EAttribute)tecnologiaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTecnologia_Llave()
  {
    return (EReference)tecnologiaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTecnologia_Metodos()
  {
    return (EReference)tecnologiaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getServicio()
  {
    return servicioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getServicio_Name()
  {
    return (EAttribute)servicioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getServicio_Metodos()
  {
    return (EReference)servicioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetodoComponente()
  {
    return metodoComponenteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMetodoComponente_Name()
  {
    return (EAttribute)metodoComponenteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetodoComponente_MetodoServicio()
  {
    return (EReference)metodoComponenteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMetodoComponente_Mensaje()
  {
    return (EAttribute)metodoComponenteEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetodoServicio()
  {
    return metodoServicioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMetodoServicio_Name()
  {
    return (EAttribute)metodoServicioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetodoServicio_TipoParametro()
  {
    return (EReference)metodoServicioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetodoServicio_TipoRetorno()
  {
    return (EReference)metodoServicioEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetodoTecnologia()
  {
    return metodoTecnologiaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMetodoTecnologia_Name()
  {
    return (EAttribute)metodoTecnologiaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetodoTecnologia_Llave()
  {
    return (EReference)metodoTecnologiaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetodoTecnologia_Valor()
  {
    return (EReference)metodoTecnologiaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEntidad()
  {
    return entidadEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInterfaz()
  {
    return interfazEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInterfaz_Name()
  {
    return (EAttribute)interfazEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInterfaz_Propiedades()
  {
    return (EReference)interfazEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPropiedad()
  {
    return propiedadEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropiedad_Name()
  {
    return (EAttribute)propiedadEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropiedad_TipoDato()
  {
    return (EAttribute)propiedadEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComponente()
  {
    return componenteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComponente_Name()
  {
    return (EAttribute)componenteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Interfaz()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Servicio()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Tecnologia()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComponente_Titulo()
  {
    return (EAttribute)componenteEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_CamposEntradas()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Botones()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_BotonesOpcionItem()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Metodos()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Arreglos()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Listado()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponente_Lista()
  {
    return (EReference)componenteEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCampoEntrada()
  {
    return campoEntradaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCampoEntrada_Contenido()
  {
    return (EAttribute)campoEntradaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCampoEntrada_Modelo()
  {
    return (EReference)campoEntradaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCampoEntrada_Campo()
  {
    return (EReference)campoEntradaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBoton()
  {
    return botonEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBoton_Contenido()
  {
    return (EAttribute)botonEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBoton_Evento()
  {
    return (EAttribute)botonEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBoton_Metodo()
  {
    return (EReference)botonEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBotonOpcionItem()
  {
    return botonOpcionItemEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBotonOpcionItem_Contenido()
  {
    return (EAttribute)botonOpcionItemEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBotonOpcionItem_Evento()
  {
    return (EAttribute)botonOpcionItemEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBotonOpcionItem_Color()
  {
    return (EAttribute)botonOpcionItemEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBotonOpcionItem_Metodo()
  {
    return (EReference)botonOpcionItemEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLista()
  {
    return listaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLista_Name()
  {
    return (EAttribute)listaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLista_Contenido()
  {
    return (EAttribute)listaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTipos()
  {
    return tiposEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTipos_TipoPrimitivo()
  {
    return (EAttribute)tiposEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTipos_TipoEstructurado()
  {
    return (EReference)tiposEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLLave()
  {
    return lLaveEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLLave_Name()
  {
    return (EAttribute)lLaveEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArreglo()
  {
    return arregloEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getListado()
  {
    return listadoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTiposArregloListado()
  {
    return tiposArregloListadoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTiposArregloListado_Name()
  {
    return (EAttribute)tiposArregloListadoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTiposArregloListado_Tipo()
  {
    return (EReference)tiposArregloListadoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getEvento()
  {
    return eventoEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getTipoDato()
  {
    return tipoDatoEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getColor()
  {
    return colorEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AppPrecioFactory getAppPrecioFactory()
  {
    return (AppPrecioFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    appPrecioEClass = createEClass(APP_PRECIO);
    createEReference(appPrecioEClass, APP_PRECIO__DOMINIO);
    createEReference(appPrecioEClass, APP_PRECIO__ARQUITECTURA);
    createEReference(appPrecioEClass, APP_PRECIO__TECNOLOGIA);

    dominioEClass = createEClass(DOMINIO);
    createEReference(dominioEClass, DOMINIO__SERVICIOS);
    createEReference(dominioEClass, DOMINIO__ENTIDADES);

    arquitecturaEClass = createEClass(ARQUITECTURA);
    createEReference(arquitecturaEClass, ARQUITECTURA__COMPONENTES);

    tecnologiaEClass = createEClass(TECNOLOGIA);
    createEAttribute(tecnologiaEClass, TECNOLOGIA__NAME);
    createEReference(tecnologiaEClass, TECNOLOGIA__LLAVE);
    createEReference(tecnologiaEClass, TECNOLOGIA__METODOS);

    servicioEClass = createEClass(SERVICIO);
    createEAttribute(servicioEClass, SERVICIO__NAME);
    createEReference(servicioEClass, SERVICIO__METODOS);

    metodoComponenteEClass = createEClass(METODO_COMPONENTE);
    createEAttribute(metodoComponenteEClass, METODO_COMPONENTE__NAME);
    createEReference(metodoComponenteEClass, METODO_COMPONENTE__METODO_SERVICIO);
    createEAttribute(metodoComponenteEClass, METODO_COMPONENTE__MENSAJE);

    metodoServicioEClass = createEClass(METODO_SERVICIO);
    createEAttribute(metodoServicioEClass, METODO_SERVICIO__NAME);
    createEReference(metodoServicioEClass, METODO_SERVICIO__TIPO_PARAMETRO);
    createEReference(metodoServicioEClass, METODO_SERVICIO__TIPO_RETORNO);

    metodoTecnologiaEClass = createEClass(METODO_TECNOLOGIA);
    createEAttribute(metodoTecnologiaEClass, METODO_TECNOLOGIA__NAME);
    createEReference(metodoTecnologiaEClass, METODO_TECNOLOGIA__LLAVE);
    createEReference(metodoTecnologiaEClass, METODO_TECNOLOGIA__VALOR);

    entidadEClass = createEClass(ENTIDAD);

    interfazEClass = createEClass(INTERFAZ);
    createEAttribute(interfazEClass, INTERFAZ__NAME);
    createEReference(interfazEClass, INTERFAZ__PROPIEDADES);

    propiedadEClass = createEClass(PROPIEDAD);
    createEAttribute(propiedadEClass, PROPIEDAD__NAME);
    createEAttribute(propiedadEClass, PROPIEDAD__TIPO_DATO);

    componenteEClass = createEClass(COMPONENTE);
    createEAttribute(componenteEClass, COMPONENTE__NAME);
    createEReference(componenteEClass, COMPONENTE__INTERFAZ);
    createEReference(componenteEClass, COMPONENTE__SERVICIO);
    createEReference(componenteEClass, COMPONENTE__TECNOLOGIA);
    createEAttribute(componenteEClass, COMPONENTE__TITULO);
    createEReference(componenteEClass, COMPONENTE__CAMPOS_ENTRADAS);
    createEReference(componenteEClass, COMPONENTE__BOTONES);
    createEReference(componenteEClass, COMPONENTE__BOTONES_OPCION_ITEM);
    createEReference(componenteEClass, COMPONENTE__METODOS);
    createEReference(componenteEClass, COMPONENTE__ARREGLOS);
    createEReference(componenteEClass, COMPONENTE__LISTADO);
    createEReference(componenteEClass, COMPONENTE__LISTA);

    campoEntradaEClass = createEClass(CAMPO_ENTRADA);
    createEAttribute(campoEntradaEClass, CAMPO_ENTRADA__CONTENIDO);
    createEReference(campoEntradaEClass, CAMPO_ENTRADA__MODELO);
    createEReference(campoEntradaEClass, CAMPO_ENTRADA__CAMPO);

    botonEClass = createEClass(BOTON);
    createEAttribute(botonEClass, BOTON__CONTENIDO);
    createEAttribute(botonEClass, BOTON__EVENTO);
    createEReference(botonEClass, BOTON__METODO);

    botonOpcionItemEClass = createEClass(BOTON_OPCION_ITEM);
    createEAttribute(botonOpcionItemEClass, BOTON_OPCION_ITEM__CONTENIDO);
    createEAttribute(botonOpcionItemEClass, BOTON_OPCION_ITEM__EVENTO);
    createEAttribute(botonOpcionItemEClass, BOTON_OPCION_ITEM__COLOR);
    createEReference(botonOpcionItemEClass, BOTON_OPCION_ITEM__METODO);

    listaEClass = createEClass(LISTA);
    createEAttribute(listaEClass, LISTA__NAME);
    createEAttribute(listaEClass, LISTA__CONTENIDO);

    tiposEClass = createEClass(TIPOS);
    createEAttribute(tiposEClass, TIPOS__TIPO_PRIMITIVO);
    createEReference(tiposEClass, TIPOS__TIPO_ESTRUCTURADO);

    lLaveEClass = createEClass(LLAVE);
    createEAttribute(lLaveEClass, LLAVE__NAME);

    arregloEClass = createEClass(ARREGLO);

    listadoEClass = createEClass(LISTADO);

    tiposArregloListadoEClass = createEClass(TIPOS_ARREGLO_LISTADO);
    createEAttribute(tiposArregloListadoEClass, TIPOS_ARREGLO_LISTADO__NAME);
    createEReference(tiposArregloListadoEClass, TIPOS_ARREGLO_LISTADO__TIPO);

    // Create enums
    eventoEEnum = createEEnum(EVENTO);
    tipoDatoEEnum = createEEnum(TIPO_DATO);
    colorEEnum = createEEnum(COLOR);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    interfazEClass.getESuperTypes().add(this.getEntidad());
    arregloEClass.getESuperTypes().add(this.getTiposArregloListado());
    listadoEClass.getESuperTypes().add(this.getTiposArregloListado());

    // Initialize classes and features; add operations and parameters
    initEClass(appPrecioEClass, AppPrecio.class, "AppPrecio", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAppPrecio_Dominio(), this.getDominio(), null, "dominio", null, 0, 1, AppPrecio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAppPrecio_Arquitectura(), this.getArquitectura(), null, "arquitectura", null, 0, 1, AppPrecio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAppPrecio_Tecnologia(), this.getTecnologia(), null, "tecnologia", null, 0, 1, AppPrecio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dominioEClass, Dominio.class, "Dominio", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDominio_Servicios(), this.getServicio(), null, "servicios", null, 0, -1, Dominio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDominio_Entidades(), this.getEntidad(), null, "entidades", null, 0, -1, Dominio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(arquitecturaEClass, Arquitectura.class, "Arquitectura", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArquitectura_Componentes(), this.getComponente(), null, "componentes", null, 0, -1, Arquitectura.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(tecnologiaEClass, Tecnologia.class, "Tecnologia", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTecnologia_Name(), ecorePackage.getEString(), "name", null, 0, 1, Tecnologia.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTecnologia_Llave(), this.getLLave(), null, "llave", null, 0, 1, Tecnologia.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTecnologia_Metodos(), this.getMetodoTecnologia(), null, "metodos", null, 0, -1, Tecnologia.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(servicioEClass, Servicio.class, "Servicio", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getServicio_Name(), ecorePackage.getEString(), "name", null, 0, 1, Servicio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getServicio_Metodos(), this.getMetodoServicio(), null, "metodos", null, 0, -1, Servicio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metodoComponenteEClass, MetodoComponente.class, "MetodoComponente", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMetodoComponente_Name(), ecorePackage.getEString(), "name", null, 0, 1, MetodoComponente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMetodoComponente_MetodoServicio(), this.getMetodoServicio(), null, "metodoServicio", null, 0, 1, MetodoComponente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMetodoComponente_Mensaje(), ecorePackage.getEString(), "mensaje", null, 0, 1, MetodoComponente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metodoServicioEClass, MetodoServicio.class, "MetodoServicio", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMetodoServicio_Name(), ecorePackage.getEString(), "name", null, 0, 1, MetodoServicio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMetodoServicio_TipoParametro(), this.getTipos(), null, "tipoParametro", null, 0, 1, MetodoServicio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMetodoServicio_TipoRetorno(), this.getTipos(), null, "tipoRetorno", null, 0, 1, MetodoServicio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metodoTecnologiaEClass, MetodoTecnologia.class, "MetodoTecnologia", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMetodoTecnologia_Name(), ecorePackage.getEString(), "name", null, 0, 1, MetodoTecnologia.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMetodoTecnologia_Llave(), this.getLLave(), null, "llave", null, 0, 1, MetodoTecnologia.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMetodoTecnologia_Valor(), this.getTiposArregloListado(), null, "valor", null, 0, 1, MetodoTecnologia.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entidadEClass, Entidad.class, "Entidad", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(interfazEClass, Interfaz.class, "Interfaz", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInterfaz_Name(), ecorePackage.getEString(), "name", null, 0, 1, Interfaz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInterfaz_Propiedades(), this.getPropiedad(), null, "propiedades", null, 0, -1, Interfaz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(propiedadEClass, Propiedad.class, "Propiedad", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPropiedad_Name(), ecorePackage.getEString(), "name", null, 0, 1, Propiedad.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPropiedad_TipoDato(), this.getTipoDato(), "tipoDato", null, 0, 1, Propiedad.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(componenteEClass, Componente.class, "Componente", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComponente_Name(), ecorePackage.getEString(), "name", null, 0, 1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Interfaz(), this.getInterfaz(), null, "interfaz", null, 0, 1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Servicio(), this.getServicio(), null, "servicio", null, 0, 1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Tecnologia(), this.getTecnologia(), null, "tecnologia", null, 0, 1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getComponente_Titulo(), ecorePackage.getEString(), "titulo", null, 0, 1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_CamposEntradas(), this.getCampoEntrada(), null, "camposEntradas", null, 0, -1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Botones(), this.getBoton(), null, "botones", null, 0, -1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_BotonesOpcionItem(), this.getBotonOpcionItem(), null, "botonesOpcionItem", null, 0, -1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Metodos(), this.getMetodoComponente(), null, "metodos", null, 0, -1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Arreglos(), this.getArreglo(), null, "arreglos", null, 0, -1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Listado(), this.getListado(), null, "listado", null, 0, -1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponente_Lista(), this.getLista(), null, "lista", null, 0, 1, Componente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(campoEntradaEClass, CampoEntrada.class, "CampoEntrada", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCampoEntrada_Contenido(), ecorePackage.getEString(), "contenido", null, 0, 1, CampoEntrada.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCampoEntrada_Modelo(), this.getListado(), null, "modelo", null, 0, 1, CampoEntrada.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCampoEntrada_Campo(), this.getPropiedad(), null, "campo", null, 0, 1, CampoEntrada.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(botonEClass, Boton.class, "Boton", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBoton_Contenido(), ecorePackage.getEString(), "contenido", null, 0, 1, Boton.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBoton_Evento(), this.getEvento(), "evento", null, 0, 1, Boton.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBoton_Metodo(), this.getMetodoComponente(), null, "metodo", null, 0, 1, Boton.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(botonOpcionItemEClass, BotonOpcionItem.class, "BotonOpcionItem", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBotonOpcionItem_Contenido(), ecorePackage.getEString(), "contenido", null, 0, 1, BotonOpcionItem.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBotonOpcionItem_Evento(), this.getEvento(), "evento", null, 0, 1, BotonOpcionItem.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBotonOpcionItem_Color(), this.getColor(), "color", null, 0, 1, BotonOpcionItem.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBotonOpcionItem_Metodo(), this.getMetodoComponente(), null, "metodo", null, 0, 1, BotonOpcionItem.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(listaEClass, Lista.class, "Lista", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLista_Name(), ecorePackage.getEString(), "name", null, 0, 1, Lista.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLista_Contenido(), ecorePackage.getEString(), "contenido", null, 0, 1, Lista.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(tiposEClass, Tipos.class, "Tipos", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTipos_TipoPrimitivo(), this.getTipoDato(), "tipoPrimitivo", null, 0, 1, Tipos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTipos_TipoEstructurado(), this.getEntidad(), null, "tipoEstructurado", null, 0, 1, Tipos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lLaveEClass, LLave.class, "LLave", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLLave_Name(), ecorePackage.getEString(), "name", null, 0, 1, LLave.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(arregloEClass, Arreglo.class, "Arreglo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(listadoEClass, Listado.class, "Listado", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(tiposArregloListadoEClass, TiposArregloListado.class, "TiposArregloListado", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTiposArregloListado_Name(), ecorePackage.getEString(), "name", null, 0, 1, TiposArregloListado.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTiposArregloListado_Tipo(), this.getEntidad(), null, "tipo", null, 0, 1, TiposArregloListado.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(eventoEEnum, Evento.class, "Evento");
    addEEnumLiteral(eventoEEnum, Evento.CLIC);

    initEEnum(tipoDatoEEnum, TipoDato.class, "TipoDato");
    addEEnumLiteral(tipoDatoEEnum, TipoDato.NUMERO);
    addEEnumLiteral(tipoDatoEEnum, TipoDato.CADENA);
    addEEnumLiteral(tipoDatoEEnum, TipoDato.NINGUNA);

    initEEnum(colorEEnum, Color.class, "Color");
    addEEnumLiteral(colorEEnum, Color.COLOR1);
    addEEnumLiteral(colorEEnum, Color.COLOR2);
    addEEnumLiteral(colorEEnum, Color.COLOR3);

    // Create resource
    createResource(eNS_URI);
  }

} //AppPrecioPackageImpl
