/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio.impl;

import co.edu.unal.dsl.appPrecio.AppPrecioPackage;
import co.edu.unal.dsl.appPrecio.CampoEntrada;
import co.edu.unal.dsl.appPrecio.Listado;
import co.edu.unal.dsl.appPrecio.Propiedad;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Campo Entrada</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.CampoEntradaImpl#getContenido <em>Contenido</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.CampoEntradaImpl#getModelo <em>Modelo</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.CampoEntradaImpl#getCampo <em>Campo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CampoEntradaImpl extends MinimalEObjectImpl.Container implements CampoEntrada
{
  /**
   * The default value of the '{@link #getContenido() <em>Contenido</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContenido()
   * @generated
   * @ordered
   */
  protected static final String CONTENIDO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContenido() <em>Contenido</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContenido()
   * @generated
   * @ordered
   */
  protected String contenido = CONTENIDO_EDEFAULT;

  /**
   * The cached value of the '{@link #getModelo() <em>Modelo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModelo()
   * @generated
   * @ordered
   */
  protected Listado modelo;

  /**
   * The cached value of the '{@link #getCampo() <em>Campo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCampo()
   * @generated
   * @ordered
   */
  protected Propiedad campo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CampoEntradaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AppPrecioPackage.Literals.CAMPO_ENTRADA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getContenido()
  {
    return contenido;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContenido(String newContenido)
  {
    String oldContenido = contenido;
    contenido = newContenido;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.CAMPO_ENTRADA__CONTENIDO, oldContenido, contenido));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Listado getModelo()
  {
    if (modelo != null && modelo.eIsProxy())
    {
      InternalEObject oldModelo = (InternalEObject)modelo;
      modelo = (Listado)eResolveProxy(oldModelo);
      if (modelo != oldModelo)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.CAMPO_ENTRADA__MODELO, oldModelo, modelo));
      }
    }
    return modelo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Listado basicGetModelo()
  {
    return modelo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setModelo(Listado newModelo)
  {
    Listado oldModelo = modelo;
    modelo = newModelo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.CAMPO_ENTRADA__MODELO, oldModelo, modelo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Propiedad getCampo()
  {
    if (campo != null && campo.eIsProxy())
    {
      InternalEObject oldCampo = (InternalEObject)campo;
      campo = (Propiedad)eResolveProxy(oldCampo);
      if (campo != oldCampo)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.CAMPO_ENTRADA__CAMPO, oldCampo, campo));
      }
    }
    return campo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Propiedad basicGetCampo()
  {
    return campo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCampo(Propiedad newCampo)
  {
    Propiedad oldCampo = campo;
    campo = newCampo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.CAMPO_ENTRADA__CAMPO, oldCampo, campo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AppPrecioPackage.CAMPO_ENTRADA__CONTENIDO:
        return getContenido();
      case AppPrecioPackage.CAMPO_ENTRADA__MODELO:
        if (resolve) return getModelo();
        return basicGetModelo();
      case AppPrecioPackage.CAMPO_ENTRADA__CAMPO:
        if (resolve) return getCampo();
        return basicGetCampo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AppPrecioPackage.CAMPO_ENTRADA__CONTENIDO:
        setContenido((String)newValue);
        return;
      case AppPrecioPackage.CAMPO_ENTRADA__MODELO:
        setModelo((Listado)newValue);
        return;
      case AppPrecioPackage.CAMPO_ENTRADA__CAMPO:
        setCampo((Propiedad)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.CAMPO_ENTRADA__CONTENIDO:
        setContenido(CONTENIDO_EDEFAULT);
        return;
      case AppPrecioPackage.CAMPO_ENTRADA__MODELO:
        setModelo((Listado)null);
        return;
      case AppPrecioPackage.CAMPO_ENTRADA__CAMPO:
        setCampo((Propiedad)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.CAMPO_ENTRADA__CONTENIDO:
        return CONTENIDO_EDEFAULT == null ? contenido != null : !CONTENIDO_EDEFAULT.equals(contenido);
      case AppPrecioPackage.CAMPO_ENTRADA__MODELO:
        return modelo != null;
      case AppPrecioPackage.CAMPO_ENTRADA__CAMPO:
        return campo != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (contenido: ");
    result.append(contenido);
    result.append(')');
    return result.toString();
  }

} //CampoEntradaImpl
