/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio.impl;

import co.edu.unal.dsl.appPrecio.AppPrecioPackage;
import co.edu.unal.dsl.appPrecio.Arreglo;
import co.edu.unal.dsl.appPrecio.Boton;
import co.edu.unal.dsl.appPrecio.BotonOpcionItem;
import co.edu.unal.dsl.appPrecio.CampoEntrada;
import co.edu.unal.dsl.appPrecio.Componente;
import co.edu.unal.dsl.appPrecio.Interfaz;
import co.edu.unal.dsl.appPrecio.Lista;
import co.edu.unal.dsl.appPrecio.Listado;
import co.edu.unal.dsl.appPrecio.MetodoComponente;
import co.edu.unal.dsl.appPrecio.Servicio;
import co.edu.unal.dsl.appPrecio.Tecnologia;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Componente</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getInterfaz <em>Interfaz</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getServicio <em>Servicio</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getTecnologia <em>Tecnologia</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getCamposEntradas <em>Campos Entradas</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getBotones <em>Botones</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getBotonesOpcionItem <em>Botones Opcion Item</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getMetodos <em>Metodos</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getArreglos <em>Arreglos</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getListado <em>Listado</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl#getLista <em>Lista</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComponenteImpl extends MinimalEObjectImpl.Container implements Componente
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getInterfaz() <em>Interfaz</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterfaz()
   * @generated
   * @ordered
   */
  protected Interfaz interfaz;

  /**
   * The cached value of the '{@link #getServicio() <em>Servicio</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServicio()
   * @generated
   * @ordered
   */
  protected Servicio servicio;

  /**
   * The cached value of the '{@link #getTecnologia() <em>Tecnologia</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTecnologia()
   * @generated
   * @ordered
   */
  protected Tecnologia tecnologia;

  /**
   * The default value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected static final String TITULO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected String titulo = TITULO_EDEFAULT;

  /**
   * The cached value of the '{@link #getCamposEntradas() <em>Campos Entradas</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCamposEntradas()
   * @generated
   * @ordered
   */
  protected EList<CampoEntrada> camposEntradas;

  /**
   * The cached value of the '{@link #getBotones() <em>Botones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBotones()
   * @generated
   * @ordered
   */
  protected EList<Boton> botones;

  /**
   * The cached value of the '{@link #getBotonesOpcionItem() <em>Botones Opcion Item</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBotonesOpcionItem()
   * @generated
   * @ordered
   */
  protected EList<BotonOpcionItem> botonesOpcionItem;

  /**
   * The cached value of the '{@link #getMetodos() <em>Metodos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetodos()
   * @generated
   * @ordered
   */
  protected EList<MetodoComponente> metodos;

  /**
   * The cached value of the '{@link #getArreglos() <em>Arreglos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArreglos()
   * @generated
   * @ordered
   */
  protected EList<Arreglo> arreglos;

  /**
   * The cached value of the '{@link #getListado() <em>Listado</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListado()
   * @generated
   * @ordered
   */
  protected EList<Listado> listado;

  /**
   * The cached value of the '{@link #getLista() <em>Lista</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLista()
   * @generated
   * @ordered
   */
  protected Lista lista;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponenteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AppPrecioPackage.Literals.COMPONENTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.COMPONENTE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interfaz getInterfaz()
  {
    if (interfaz != null && interfaz.eIsProxy())
    {
      InternalEObject oldInterfaz = (InternalEObject)interfaz;
      interfaz = (Interfaz)eResolveProxy(oldInterfaz);
      if (interfaz != oldInterfaz)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.COMPONENTE__INTERFAZ, oldInterfaz, interfaz));
      }
    }
    return interfaz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Interfaz basicGetInterfaz()
  {
    return interfaz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInterfaz(Interfaz newInterfaz)
  {
    Interfaz oldInterfaz = interfaz;
    interfaz = newInterfaz;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.COMPONENTE__INTERFAZ, oldInterfaz, interfaz));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Servicio getServicio()
  {
    if (servicio != null && servicio.eIsProxy())
    {
      InternalEObject oldServicio = (InternalEObject)servicio;
      servicio = (Servicio)eResolveProxy(oldServicio);
      if (servicio != oldServicio)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.COMPONENTE__SERVICIO, oldServicio, servicio));
      }
    }
    return servicio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Servicio basicGetServicio()
  {
    return servicio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setServicio(Servicio newServicio)
  {
    Servicio oldServicio = servicio;
    servicio = newServicio;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.COMPONENTE__SERVICIO, oldServicio, servicio));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Tecnologia getTecnologia()
  {
    if (tecnologia != null && tecnologia.eIsProxy())
    {
      InternalEObject oldTecnologia = (InternalEObject)tecnologia;
      tecnologia = (Tecnologia)eResolveProxy(oldTecnologia);
      if (tecnologia != oldTecnologia)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.COMPONENTE__TECNOLOGIA, oldTecnologia, tecnologia));
      }
    }
    return tecnologia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Tecnologia basicGetTecnologia()
  {
    return tecnologia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTecnologia(Tecnologia newTecnologia)
  {
    Tecnologia oldTecnologia = tecnologia;
    tecnologia = newTecnologia;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.COMPONENTE__TECNOLOGIA, oldTecnologia, tecnologia));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitulo()
  {
    return titulo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitulo(String newTitulo)
  {
    String oldTitulo = titulo;
    titulo = newTitulo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.COMPONENTE__TITULO, oldTitulo, titulo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CampoEntrada> getCamposEntradas()
  {
    if (camposEntradas == null)
    {
      camposEntradas = new EObjectContainmentEList<CampoEntrada>(CampoEntrada.class, this, AppPrecioPackage.COMPONENTE__CAMPOS_ENTRADAS);
    }
    return camposEntradas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Boton> getBotones()
  {
    if (botones == null)
    {
      botones = new EObjectContainmentEList<Boton>(Boton.class, this, AppPrecioPackage.COMPONENTE__BOTONES);
    }
    return botones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BotonOpcionItem> getBotonesOpcionItem()
  {
    if (botonesOpcionItem == null)
    {
      botonesOpcionItem = new EObjectContainmentEList<BotonOpcionItem>(BotonOpcionItem.class, this, AppPrecioPackage.COMPONENTE__BOTONES_OPCION_ITEM);
    }
    return botonesOpcionItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MetodoComponente> getMetodos()
  {
    if (metodos == null)
    {
      metodos = new EObjectContainmentEList<MetodoComponente>(MetodoComponente.class, this, AppPrecioPackage.COMPONENTE__METODOS);
    }
    return metodos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Arreglo> getArreglos()
  {
    if (arreglos == null)
    {
      arreglos = new EObjectContainmentEList<Arreglo>(Arreglo.class, this, AppPrecioPackage.COMPONENTE__ARREGLOS);
    }
    return arreglos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Listado> getListado()
  {
    if (listado == null)
    {
      listado = new EObjectContainmentEList<Listado>(Listado.class, this, AppPrecioPackage.COMPONENTE__LISTADO);
    }
    return listado;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lista getLista()
  {
    return lista;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLista(Lista newLista, NotificationChain msgs)
  {
    Lista oldLista = lista;
    lista = newLista;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AppPrecioPackage.COMPONENTE__LISTA, oldLista, newLista);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLista(Lista newLista)
  {
    if (newLista != lista)
    {
      NotificationChain msgs = null;
      if (lista != null)
        msgs = ((InternalEObject)lista).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AppPrecioPackage.COMPONENTE__LISTA, null, msgs);
      if (newLista != null)
        msgs = ((InternalEObject)newLista).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AppPrecioPackage.COMPONENTE__LISTA, null, msgs);
      msgs = basicSetLista(newLista, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.COMPONENTE__LISTA, newLista, newLista));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AppPrecioPackage.COMPONENTE__CAMPOS_ENTRADAS:
        return ((InternalEList<?>)getCamposEntradas()).basicRemove(otherEnd, msgs);
      case AppPrecioPackage.COMPONENTE__BOTONES:
        return ((InternalEList<?>)getBotones()).basicRemove(otherEnd, msgs);
      case AppPrecioPackage.COMPONENTE__BOTONES_OPCION_ITEM:
        return ((InternalEList<?>)getBotonesOpcionItem()).basicRemove(otherEnd, msgs);
      case AppPrecioPackage.COMPONENTE__METODOS:
        return ((InternalEList<?>)getMetodos()).basicRemove(otherEnd, msgs);
      case AppPrecioPackage.COMPONENTE__ARREGLOS:
        return ((InternalEList<?>)getArreglos()).basicRemove(otherEnd, msgs);
      case AppPrecioPackage.COMPONENTE__LISTADO:
        return ((InternalEList<?>)getListado()).basicRemove(otherEnd, msgs);
      case AppPrecioPackage.COMPONENTE__LISTA:
        return basicSetLista(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AppPrecioPackage.COMPONENTE__NAME:
        return getName();
      case AppPrecioPackage.COMPONENTE__INTERFAZ:
        if (resolve) return getInterfaz();
        return basicGetInterfaz();
      case AppPrecioPackage.COMPONENTE__SERVICIO:
        if (resolve) return getServicio();
        return basicGetServicio();
      case AppPrecioPackage.COMPONENTE__TECNOLOGIA:
        if (resolve) return getTecnologia();
        return basicGetTecnologia();
      case AppPrecioPackage.COMPONENTE__TITULO:
        return getTitulo();
      case AppPrecioPackage.COMPONENTE__CAMPOS_ENTRADAS:
        return getCamposEntradas();
      case AppPrecioPackage.COMPONENTE__BOTONES:
        return getBotones();
      case AppPrecioPackage.COMPONENTE__BOTONES_OPCION_ITEM:
        return getBotonesOpcionItem();
      case AppPrecioPackage.COMPONENTE__METODOS:
        return getMetodos();
      case AppPrecioPackage.COMPONENTE__ARREGLOS:
        return getArreglos();
      case AppPrecioPackage.COMPONENTE__LISTADO:
        return getListado();
      case AppPrecioPackage.COMPONENTE__LISTA:
        return getLista();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AppPrecioPackage.COMPONENTE__NAME:
        setName((String)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__INTERFAZ:
        setInterfaz((Interfaz)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__SERVICIO:
        setServicio((Servicio)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__TECNOLOGIA:
        setTecnologia((Tecnologia)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__TITULO:
        setTitulo((String)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__CAMPOS_ENTRADAS:
        getCamposEntradas().clear();
        getCamposEntradas().addAll((Collection<? extends CampoEntrada>)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__BOTONES:
        getBotones().clear();
        getBotones().addAll((Collection<? extends Boton>)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__BOTONES_OPCION_ITEM:
        getBotonesOpcionItem().clear();
        getBotonesOpcionItem().addAll((Collection<? extends BotonOpcionItem>)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__METODOS:
        getMetodos().clear();
        getMetodos().addAll((Collection<? extends MetodoComponente>)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__ARREGLOS:
        getArreglos().clear();
        getArreglos().addAll((Collection<? extends Arreglo>)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__LISTADO:
        getListado().clear();
        getListado().addAll((Collection<? extends Listado>)newValue);
        return;
      case AppPrecioPackage.COMPONENTE__LISTA:
        setLista((Lista)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.COMPONENTE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AppPrecioPackage.COMPONENTE__INTERFAZ:
        setInterfaz((Interfaz)null);
        return;
      case AppPrecioPackage.COMPONENTE__SERVICIO:
        setServicio((Servicio)null);
        return;
      case AppPrecioPackage.COMPONENTE__TECNOLOGIA:
        setTecnologia((Tecnologia)null);
        return;
      case AppPrecioPackage.COMPONENTE__TITULO:
        setTitulo(TITULO_EDEFAULT);
        return;
      case AppPrecioPackage.COMPONENTE__CAMPOS_ENTRADAS:
        getCamposEntradas().clear();
        return;
      case AppPrecioPackage.COMPONENTE__BOTONES:
        getBotones().clear();
        return;
      case AppPrecioPackage.COMPONENTE__BOTONES_OPCION_ITEM:
        getBotonesOpcionItem().clear();
        return;
      case AppPrecioPackage.COMPONENTE__METODOS:
        getMetodos().clear();
        return;
      case AppPrecioPackage.COMPONENTE__ARREGLOS:
        getArreglos().clear();
        return;
      case AppPrecioPackage.COMPONENTE__LISTADO:
        getListado().clear();
        return;
      case AppPrecioPackage.COMPONENTE__LISTA:
        setLista((Lista)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.COMPONENTE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AppPrecioPackage.COMPONENTE__INTERFAZ:
        return interfaz != null;
      case AppPrecioPackage.COMPONENTE__SERVICIO:
        return servicio != null;
      case AppPrecioPackage.COMPONENTE__TECNOLOGIA:
        return tecnologia != null;
      case AppPrecioPackage.COMPONENTE__TITULO:
        return TITULO_EDEFAULT == null ? titulo != null : !TITULO_EDEFAULT.equals(titulo);
      case AppPrecioPackage.COMPONENTE__CAMPOS_ENTRADAS:
        return camposEntradas != null && !camposEntradas.isEmpty();
      case AppPrecioPackage.COMPONENTE__BOTONES:
        return botones != null && !botones.isEmpty();
      case AppPrecioPackage.COMPONENTE__BOTONES_OPCION_ITEM:
        return botonesOpcionItem != null && !botonesOpcionItem.isEmpty();
      case AppPrecioPackage.COMPONENTE__METODOS:
        return metodos != null && !metodos.isEmpty();
      case AppPrecioPackage.COMPONENTE__ARREGLOS:
        return arreglos != null && !arreglos.isEmpty();
      case AppPrecioPackage.COMPONENTE__LISTADO:
        return listado != null && !listado.isEmpty();
      case AppPrecioPackage.COMPONENTE__LISTA:
        return lista != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", titulo: ");
    result.append(titulo);
    result.append(')');
    return result.toString();
  }

} //ComponenteImpl
