/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio.impl;

import co.edu.unal.dsl.appPrecio.AppPrecioPackage;
import co.edu.unal.dsl.appPrecio.MetodoServicio;
import co.edu.unal.dsl.appPrecio.Tipos;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Metodo Servicio</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.MetodoServicioImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.MetodoServicioImpl#getTipoParametro <em>Tipo Parametro</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.MetodoServicioImpl#getTipoRetorno <em>Tipo Retorno</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MetodoServicioImpl extends MinimalEObjectImpl.Container implements MetodoServicio
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTipoParametro() <em>Tipo Parametro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoParametro()
   * @generated
   * @ordered
   */
  protected Tipos tipoParametro;

  /**
   * The cached value of the '{@link #getTipoRetorno() <em>Tipo Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoRetorno()
   * @generated
   * @ordered
   */
  protected Tipos tipoRetorno;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MetodoServicioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AppPrecioPackage.Literals.METODO_SERVICIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_SERVICIO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Tipos getTipoParametro()
  {
    return tipoParametro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipoParametro(Tipos newTipoParametro, NotificationChain msgs)
  {
    Tipos oldTipoParametro = tipoParametro;
    tipoParametro = newTipoParametro;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO, oldTipoParametro, newTipoParametro);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoParametro(Tipos newTipoParametro)
  {
    if (newTipoParametro != tipoParametro)
    {
      NotificationChain msgs = null;
      if (tipoParametro != null)
        msgs = ((InternalEObject)tipoParametro).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO, null, msgs);
      if (newTipoParametro != null)
        msgs = ((InternalEObject)newTipoParametro).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO, null, msgs);
      msgs = basicSetTipoParametro(newTipoParametro, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO, newTipoParametro, newTipoParametro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Tipos getTipoRetorno()
  {
    return tipoRetorno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipoRetorno(Tipos newTipoRetorno, NotificationChain msgs)
  {
    Tipos oldTipoRetorno = tipoRetorno;
    tipoRetorno = newTipoRetorno;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO, oldTipoRetorno, newTipoRetorno);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoRetorno(Tipos newTipoRetorno)
  {
    if (newTipoRetorno != tipoRetorno)
    {
      NotificationChain msgs = null;
      if (tipoRetorno != null)
        msgs = ((InternalEObject)tipoRetorno).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO, null, msgs);
      if (newTipoRetorno != null)
        msgs = ((InternalEObject)newTipoRetorno).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO, null, msgs);
      msgs = basicSetTipoRetorno(newTipoRetorno, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO, newTipoRetorno, newTipoRetorno));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO:
        return basicSetTipoParametro(null, msgs);
      case AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO:
        return basicSetTipoRetorno(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_SERVICIO__NAME:
        return getName();
      case AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO:
        return getTipoParametro();
      case AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO:
        return getTipoRetorno();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_SERVICIO__NAME:
        setName((String)newValue);
        return;
      case AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO:
        setTipoParametro((Tipos)newValue);
        return;
      case AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO:
        setTipoRetorno((Tipos)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_SERVICIO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO:
        setTipoParametro((Tipos)null);
        return;
      case AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO:
        setTipoRetorno((Tipos)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_SERVICIO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AppPrecioPackage.METODO_SERVICIO__TIPO_PARAMETRO:
        return tipoParametro != null;
      case AppPrecioPackage.METODO_SERVICIO__TIPO_RETORNO:
        return tipoRetorno != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //MetodoServicioImpl
