/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio.impl;

import co.edu.unal.dsl.appPrecio.AppPrecioPackage;
import co.edu.unal.dsl.appPrecio.LLave;
import co.edu.unal.dsl.appPrecio.MetodoTecnologia;
import co.edu.unal.dsl.appPrecio.TiposArregloListado;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Metodo Tecnologia</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.MetodoTecnologiaImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.MetodoTecnologiaImpl#getLlave <em>Llave</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.MetodoTecnologiaImpl#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MetodoTecnologiaImpl extends MinimalEObjectImpl.Container implements MetodoTecnologia
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getLlave() <em>Llave</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLlave()
   * @generated
   * @ordered
   */
  protected LLave llave;

  /**
   * The cached value of the '{@link #getValor() <em>Valor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValor()
   * @generated
   * @ordered
   */
  protected TiposArregloListado valor;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MetodoTecnologiaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AppPrecioPackage.Literals.METODO_TECNOLOGIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_TECNOLOGIA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LLave getLlave()
  {
    if (llave != null && llave.eIsProxy())
    {
      InternalEObject oldLlave = (InternalEObject)llave;
      llave = (LLave)eResolveProxy(oldLlave);
      if (llave != oldLlave)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.METODO_TECNOLOGIA__LLAVE, oldLlave, llave));
      }
    }
    return llave;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LLave basicGetLlave()
  {
    return llave;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLlave(LLave newLlave)
  {
    LLave oldLlave = llave;
    llave = newLlave;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_TECNOLOGIA__LLAVE, oldLlave, llave));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TiposArregloListado getValor()
  {
    if (valor != null && valor.eIsProxy())
    {
      InternalEObject oldValor = (InternalEObject)valor;
      valor = (TiposArregloListado)eResolveProxy(oldValor);
      if (valor != oldValor)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.METODO_TECNOLOGIA__VALOR, oldValor, valor));
      }
    }
    return valor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TiposArregloListado basicGetValor()
  {
    return valor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValor(TiposArregloListado newValor)
  {
    TiposArregloListado oldValor = valor;
    valor = newValor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.METODO_TECNOLOGIA__VALOR, oldValor, valor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_TECNOLOGIA__NAME:
        return getName();
      case AppPrecioPackage.METODO_TECNOLOGIA__LLAVE:
        if (resolve) return getLlave();
        return basicGetLlave();
      case AppPrecioPackage.METODO_TECNOLOGIA__VALOR:
        if (resolve) return getValor();
        return basicGetValor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_TECNOLOGIA__NAME:
        setName((String)newValue);
        return;
      case AppPrecioPackage.METODO_TECNOLOGIA__LLAVE:
        setLlave((LLave)newValue);
        return;
      case AppPrecioPackage.METODO_TECNOLOGIA__VALOR:
        setValor((TiposArregloListado)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_TECNOLOGIA__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AppPrecioPackage.METODO_TECNOLOGIA__LLAVE:
        setLlave((LLave)null);
        return;
      case AppPrecioPackage.METODO_TECNOLOGIA__VALOR:
        setValor((TiposArregloListado)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.METODO_TECNOLOGIA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AppPrecioPackage.METODO_TECNOLOGIA__LLAVE:
        return llave != null;
      case AppPrecioPackage.METODO_TECNOLOGIA__VALOR:
        return valor != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //MetodoTecnologiaImpl
