/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio.impl;

import co.edu.unal.dsl.appPrecio.AppPrecioPackage;
import co.edu.unal.dsl.appPrecio.Entidad;
import co.edu.unal.dsl.appPrecio.TipoDato;
import co.edu.unal.dsl.appPrecio.Tipos;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tipos</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.TiposImpl#getTipoPrimitivo <em>Tipo Primitivo</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.impl.TiposImpl#getTipoEstructurado <em>Tipo Estructurado</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TiposImpl extends MinimalEObjectImpl.Container implements Tipos
{
  /**
   * The default value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected static final TipoDato TIPO_PRIMITIVO_EDEFAULT = TipoDato.NUMERO;

  /**
   * The cached value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected TipoDato tipoPrimitivo = TIPO_PRIMITIVO_EDEFAULT;

  /**
   * The cached value of the '{@link #getTipoEstructurado() <em>Tipo Estructurado</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoEstructurado()
   * @generated
   * @ordered
   */
  protected Entidad tipoEstructurado;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TiposImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AppPrecioPackage.Literals.TIPOS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TipoDato getTipoPrimitivo()
  {
    return tipoPrimitivo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoPrimitivo(TipoDato newTipoPrimitivo)
  {
    TipoDato oldTipoPrimitivo = tipoPrimitivo;
    tipoPrimitivo = newTipoPrimitivo == null ? TIPO_PRIMITIVO_EDEFAULT : newTipoPrimitivo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.TIPOS__TIPO_PRIMITIVO, oldTipoPrimitivo, tipoPrimitivo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entidad getTipoEstructurado()
  {
    if (tipoEstructurado != null && tipoEstructurado.eIsProxy())
    {
      InternalEObject oldTipoEstructurado = (InternalEObject)tipoEstructurado;
      tipoEstructurado = (Entidad)eResolveProxy(oldTipoEstructurado);
      if (tipoEstructurado != oldTipoEstructurado)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AppPrecioPackage.TIPOS__TIPO_ESTRUCTURADO, oldTipoEstructurado, tipoEstructurado));
      }
    }
    return tipoEstructurado;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidad basicGetTipoEstructurado()
  {
    return tipoEstructurado;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoEstructurado(Entidad newTipoEstructurado)
  {
    Entidad oldTipoEstructurado = tipoEstructurado;
    tipoEstructurado = newTipoEstructurado;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPrecioPackage.TIPOS__TIPO_ESTRUCTURADO, oldTipoEstructurado, tipoEstructurado));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AppPrecioPackage.TIPOS__TIPO_PRIMITIVO:
        return getTipoPrimitivo();
      case AppPrecioPackage.TIPOS__TIPO_ESTRUCTURADO:
        if (resolve) return getTipoEstructurado();
        return basicGetTipoEstructurado();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AppPrecioPackage.TIPOS__TIPO_PRIMITIVO:
        setTipoPrimitivo((TipoDato)newValue);
        return;
      case AppPrecioPackage.TIPOS__TIPO_ESTRUCTURADO:
        setTipoEstructurado((Entidad)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.TIPOS__TIPO_PRIMITIVO:
        setTipoPrimitivo(TIPO_PRIMITIVO_EDEFAULT);
        return;
      case AppPrecioPackage.TIPOS__TIPO_ESTRUCTURADO:
        setTipoEstructurado((Entidad)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AppPrecioPackage.TIPOS__TIPO_PRIMITIVO:
        return tipoPrimitivo != TIPO_PRIMITIVO_EDEFAULT;
      case AppPrecioPackage.TIPOS__TIPO_ESTRUCTURADO:
        return tipoEstructurado != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tipoPrimitivo: ");
    result.append(tipoPrimitivo);
    result.append(')');
    return result.toString();
  }

} //TiposImpl
