/*
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.ide.contentassist.antlr;

import co.edu.unal.dsl.ide.contentassist.antlr.internal.InternalAppPrecioParser;
import co.edu.unal.dsl.services.AppPrecioGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AppPrecioParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AppPrecioGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AppPrecioGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTiposAccess().getAlternatives(), "rule__Tipos__Alternatives");
			builder.put(grammarAccess.getTiposArregloListadoAccess().getAlternatives(), "rule__TiposArregloListado__Alternatives");
			builder.put(grammarAccess.getTipoDatoAccess().getAlternatives(), "rule__TipoDato__Alternatives");
			builder.put(grammarAccess.getColorAccess().getAlternatives(), "rule__Color__Alternatives");
			builder.put(grammarAccess.getAppPrecioAccess().getGroup(), "rule__AppPrecio__Group__0");
			builder.put(grammarAccess.getDominioAccess().getGroup(), "rule__Dominio__Group__0");
			builder.put(grammarAccess.getArquitecturaAccess().getGroup(), "rule__Arquitectura__Group__0");
			builder.put(grammarAccess.getTecnologiaAccess().getGroup(), "rule__Tecnologia__Group__0");
			builder.put(grammarAccess.getServicioAccess().getGroup(), "rule__Servicio__Group__0");
			builder.put(grammarAccess.getMetodoComponenteAccess().getGroup(), "rule__MetodoComponente__Group__0");
			builder.put(grammarAccess.getMetodoComponenteAccess().getGroup_3(), "rule__MetodoComponente__Group_3__0");
			builder.put(grammarAccess.getMetodoComponenteAccess().getGroup_4(), "rule__MetodoComponente__Group_4__0");
			builder.put(grammarAccess.getMetodoServicioAccess().getGroup(), "rule__MetodoServicio__Group__0");
			builder.put(grammarAccess.getMetodoServicioAccess().getGroup_3(), "rule__MetodoServicio__Group_3__0");
			builder.put(grammarAccess.getMetodoServicioAccess().getGroup_4(), "rule__MetodoServicio__Group_4__0");
			builder.put(grammarAccess.getMetodoTecnologiaAccess().getGroup(), "rule__MetodoTecnologia__Group__0");
			builder.put(grammarAccess.getMetodoTecnologiaAccess().getGroup_3(), "rule__MetodoTecnologia__Group_3__0");
			builder.put(grammarAccess.getMetodoTecnologiaAccess().getGroup_4(), "rule__MetodoTecnologia__Group_4__0");
			builder.put(grammarAccess.getInterfazAccess().getGroup(), "rule__Interfaz__Group__0");
			builder.put(grammarAccess.getPropiedadAccess().getGroup(), "rule__Propiedad__Group__0");
			builder.put(grammarAccess.getComponenteAccess().getGroup(), "rule__Componente__Group__0");
			builder.put(grammarAccess.getCampoEntradaAccess().getGroup(), "rule__CampoEntrada__Group__0");
			builder.put(grammarAccess.getBotonAccess().getGroup(), "rule__Boton__Group__0");
			builder.put(grammarAccess.getBotonAccess().getGroup_8(), "rule__Boton__Group_8__0");
			builder.put(grammarAccess.getBotonOpcionItemAccess().getGroup(), "rule__BotonOpcionItem__Group__0");
			builder.put(grammarAccess.getBotonOpcionItemAccess().getGroup_8(), "rule__BotonOpcionItem__Group_8__0");
			builder.put(grammarAccess.getBotonOpcionItemAccess().getGroup_9(), "rule__BotonOpcionItem__Group_9__0");
			builder.put(grammarAccess.getListaAccess().getGroup(), "rule__Lista__Group__0");
			builder.put(grammarAccess.getArregloAccess().getGroup(), "rule__Arreglo__Group__0");
			builder.put(grammarAccess.getArregloAccess().getGroup_2(), "rule__Arreglo__Group_2__0");
			builder.put(grammarAccess.getListadoAccess().getGroup(), "rule__Listado__Group__0");
			builder.put(grammarAccess.getAppPrecioAccess().getDominioAssignment_2(), "rule__AppPrecio__DominioAssignment_2");
			builder.put(grammarAccess.getAppPrecioAccess().getArquitecturaAssignment_3(), "rule__AppPrecio__ArquitecturaAssignment_3");
			builder.put(grammarAccess.getAppPrecioAccess().getTecnologiaAssignment_4(), "rule__AppPrecio__TecnologiaAssignment_4");
			builder.put(grammarAccess.getDominioAccess().getServiciosAssignment_3(), "rule__Dominio__ServiciosAssignment_3");
			builder.put(grammarAccess.getDominioAccess().getEntidadesAssignment_4(), "rule__Dominio__EntidadesAssignment_4");
			builder.put(grammarAccess.getArquitecturaAccess().getComponentesAssignment_3(), "rule__Arquitectura__ComponentesAssignment_3");
			builder.put(grammarAccess.getTecnologiaAccess().getNameAssignment_1(), "rule__Tecnologia__NameAssignment_1");
			builder.put(grammarAccess.getTecnologiaAccess().getLlaveAssignment_5(), "rule__Tecnologia__LlaveAssignment_5");
			builder.put(grammarAccess.getTecnologiaAccess().getMetodosAssignment_6(), "rule__Tecnologia__MetodosAssignment_6");
			builder.put(grammarAccess.getServicioAccess().getNameAssignment_1(), "rule__Servicio__NameAssignment_1");
			builder.put(grammarAccess.getServicioAccess().getMetodosAssignment_3(), "rule__Servicio__MetodosAssignment_3");
			builder.put(grammarAccess.getMetodoComponenteAccess().getNameAssignment_1(), "rule__MetodoComponente__NameAssignment_1");
			builder.put(grammarAccess.getMetodoComponenteAccess().getMetodoServicioAssignment_3_2(), "rule__MetodoComponente__MetodoServicioAssignment_3_2");
			builder.put(grammarAccess.getMetodoComponenteAccess().getMensajeAssignment_4_2(), "rule__MetodoComponente__MensajeAssignment_4_2");
			builder.put(grammarAccess.getMetodoServicioAccess().getNameAssignment_1(), "rule__MetodoServicio__NameAssignment_1");
			builder.put(grammarAccess.getMetodoServicioAccess().getTipoParametroAssignment_3_2(), "rule__MetodoServicio__TipoParametroAssignment_3_2");
			builder.put(grammarAccess.getMetodoServicioAccess().getTipoRetornoAssignment_4_2(), "rule__MetodoServicio__TipoRetornoAssignment_4_2");
			builder.put(grammarAccess.getMetodoTecnologiaAccess().getNameAssignment_1(), "rule__MetodoTecnologia__NameAssignment_1");
			builder.put(grammarAccess.getMetodoTecnologiaAccess().getLlaveAssignment_3_2(), "rule__MetodoTecnologia__LlaveAssignment_3_2");
			builder.put(grammarAccess.getMetodoTecnologiaAccess().getValorAssignment_4_2(), "rule__MetodoTecnologia__ValorAssignment_4_2");
			builder.put(grammarAccess.getInterfazAccess().getNameAssignment_1(), "rule__Interfaz__NameAssignment_1");
			builder.put(grammarAccess.getInterfazAccess().getPropiedadesAssignment_3(), "rule__Interfaz__PropiedadesAssignment_3");
			builder.put(grammarAccess.getPropiedadAccess().getNameAssignment_0(), "rule__Propiedad__NameAssignment_0");
			builder.put(grammarAccess.getPropiedadAccess().getTipoDatoAssignment_2(), "rule__Propiedad__TipoDatoAssignment_2");
			builder.put(grammarAccess.getComponenteAccess().getNameAssignment_1(), "rule__Componente__NameAssignment_1");
			builder.put(grammarAccess.getComponenteAccess().getInterfazAssignment_5(), "rule__Componente__InterfazAssignment_5");
			builder.put(grammarAccess.getComponenteAccess().getServicioAssignment_8(), "rule__Componente__ServicioAssignment_8");
			builder.put(grammarAccess.getComponenteAccess().getTecnologiaAssignment_11(), "rule__Componente__TecnologiaAssignment_11");
			builder.put(grammarAccess.getComponenteAccess().getTituloAssignment_14(), "rule__Componente__TituloAssignment_14");
			builder.put(grammarAccess.getComponenteAccess().getCamposEntradasAssignment_15(), "rule__Componente__CamposEntradasAssignment_15");
			builder.put(grammarAccess.getComponenteAccess().getBotonesAssignment_16(), "rule__Componente__BotonesAssignment_16");
			builder.put(grammarAccess.getComponenteAccess().getBotonesOpcionItemAssignment_17(), "rule__Componente__BotonesOpcionItemAssignment_17");
			builder.put(grammarAccess.getComponenteAccess().getMetodosAssignment_18(), "rule__Componente__MetodosAssignment_18");
			builder.put(grammarAccess.getComponenteAccess().getArreglosAssignment_19(), "rule__Componente__ArreglosAssignment_19");
			builder.put(grammarAccess.getComponenteAccess().getListadoAssignment_20(), "rule__Componente__ListadoAssignment_20");
			builder.put(grammarAccess.getComponenteAccess().getListaAssignment_21(), "rule__Componente__ListaAssignment_21");
			builder.put(grammarAccess.getCampoEntradaAccess().getContenidoAssignment_4(), "rule__CampoEntrada__ContenidoAssignment_4");
			builder.put(grammarAccess.getCampoEntradaAccess().getModeloAssignment_7(), "rule__CampoEntrada__ModeloAssignment_7");
			builder.put(grammarAccess.getCampoEntradaAccess().getCampoAssignment_10(), "rule__CampoEntrada__CampoAssignment_10");
			builder.put(grammarAccess.getBotonAccess().getContenidoAssignment_4(), "rule__Boton__ContenidoAssignment_4");
			builder.put(grammarAccess.getBotonAccess().getEventoAssignment_7(), "rule__Boton__EventoAssignment_7");
			builder.put(grammarAccess.getBotonAccess().getMetodoAssignment_8_2(), "rule__Boton__MetodoAssignment_8_2");
			builder.put(grammarAccess.getBotonOpcionItemAccess().getContenidoAssignment_4(), "rule__BotonOpcionItem__ContenidoAssignment_4");
			builder.put(grammarAccess.getBotonOpcionItemAccess().getEventoAssignment_7(), "rule__BotonOpcionItem__EventoAssignment_7");
			builder.put(grammarAccess.getBotonOpcionItemAccess().getColorAssignment_8_2(), "rule__BotonOpcionItem__ColorAssignment_8_2");
			builder.put(grammarAccess.getBotonOpcionItemAccess().getMetodoAssignment_9_2(), "rule__BotonOpcionItem__MetodoAssignment_9_2");
			builder.put(grammarAccess.getListaAccess().getNameAssignment_1(), "rule__Lista__NameAssignment_1");
			builder.put(grammarAccess.getListaAccess().getContenidoAssignment_5(), "rule__Lista__ContenidoAssignment_5");
			builder.put(grammarAccess.getTiposAccess().getTipoPrimitivoAssignment_0(), "rule__Tipos__TipoPrimitivoAssignment_0");
			builder.put(grammarAccess.getTiposAccess().getTipoEstructuradoAssignment_1(), "rule__Tipos__TipoEstructuradoAssignment_1");
			builder.put(grammarAccess.getLLaveAccess().getNameAssignment(), "rule__LLave__NameAssignment");
			builder.put(grammarAccess.getArregloAccess().getNameAssignment_1(), "rule__Arreglo__NameAssignment_1");
			builder.put(grammarAccess.getArregloAccess().getTipoAssignment_2_1(), "rule__Arreglo__TipoAssignment_2_1");
			builder.put(grammarAccess.getListadoAccess().getNameAssignment_1(), "rule__Listado__NameAssignment_1");
			builder.put(grammarAccess.getListadoAccess().getTipoAssignment_3(), "rule__Listado__TipoAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AppPrecioGrammarAccess grammarAccess;

	@Override
	protected InternalAppPrecioParser createParser() {
		InternalAppPrecioParser result = new InternalAppPrecioParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AppPrecioGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AppPrecioGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
