/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.edu.unal.dsl.appPrecio.AppPrecioFactory
 * @model kind="package"
 * @generated
 */
public interface AppPrecioPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "appPrecio";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.edu.co/unal/dsl/AppPrecio";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "appPrecio";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AppPrecioPackage eINSTANCE = co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl.init();

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.AppPrecioImpl <em>App Precio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getAppPrecio()
   * @generated
   */
  int APP_PRECIO = 0;

  /**
   * The feature id for the '<em><b>Dominio</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_PRECIO__DOMINIO = 0;

  /**
   * The feature id for the '<em><b>Arquitectura</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_PRECIO__ARQUITECTURA = 1;

  /**
   * The feature id for the '<em><b>Tecnologia</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_PRECIO__TECNOLOGIA = 2;

  /**
   * The number of structural features of the '<em>App Precio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_PRECIO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.DominioImpl <em>Dominio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.DominioImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getDominio()
   * @generated
   */
  int DOMINIO = 1;

  /**
   * The feature id for the '<em><b>Servicios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMINIO__SERVICIOS = 0;

  /**
   * The feature id for the '<em><b>Entidades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMINIO__ENTIDADES = 1;

  /**
   * The number of structural features of the '<em>Dominio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMINIO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.ArquitecturaImpl <em>Arquitectura</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.ArquitecturaImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getArquitectura()
   * @generated
   */
  int ARQUITECTURA = 2;

  /**
   * The feature id for the '<em><b>Componentes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARQUITECTURA__COMPONENTES = 0;

  /**
   * The number of structural features of the '<em>Arquitectura</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARQUITECTURA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.TecnologiaImpl <em>Tecnologia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.TecnologiaImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTecnologia()
   * @generated
   */
  int TECNOLOGIA = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TECNOLOGIA__NAME = 0;

  /**
   * The feature id for the '<em><b>Llave</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TECNOLOGIA__LLAVE = 1;

  /**
   * The feature id for the '<em><b>Metodos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TECNOLOGIA__METODOS = 2;

  /**
   * The number of structural features of the '<em>Tecnologia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TECNOLOGIA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.ServicioImpl <em>Servicio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.ServicioImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getServicio()
   * @generated
   */
  int SERVICIO = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO__NAME = 0;

  /**
   * The feature id for the '<em><b>Metodos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO__METODOS = 1;

  /**
   * The number of structural features of the '<em>Servicio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.MetodoComponenteImpl <em>Metodo Componente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.MetodoComponenteImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getMetodoComponente()
   * @generated
   */
  int METODO_COMPONENTE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_COMPONENTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Metodo Servicio</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_COMPONENTE__METODO_SERVICIO = 1;

  /**
   * The feature id for the '<em><b>Mensaje</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_COMPONENTE__MENSAJE = 2;

  /**
   * The number of structural features of the '<em>Metodo Componente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_COMPONENTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.MetodoServicioImpl <em>Metodo Servicio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.MetodoServicioImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getMetodoServicio()
   * @generated
   */
  int METODO_SERVICIO = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_SERVICIO__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo Parametro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_SERVICIO__TIPO_PARAMETRO = 1;

  /**
   * The feature id for the '<em><b>Tipo Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_SERVICIO__TIPO_RETORNO = 2;

  /**
   * The number of structural features of the '<em>Metodo Servicio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_SERVICIO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.MetodoTecnologiaImpl <em>Metodo Tecnologia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.MetodoTecnologiaImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getMetodoTecnologia()
   * @generated
   */
  int METODO_TECNOLOGIA = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_TECNOLOGIA__NAME = 0;

  /**
   * The feature id for the '<em><b>Llave</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_TECNOLOGIA__LLAVE = 1;

  /**
   * The feature id for the '<em><b>Valor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_TECNOLOGIA__VALOR = 2;

  /**
   * The number of structural features of the '<em>Metodo Tecnologia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_TECNOLOGIA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.EntidadImpl <em>Entidad</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.EntidadImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getEntidad()
   * @generated
   */
  int ENTIDAD = 8;

  /**
   * The number of structural features of the '<em>Entidad</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.InterfazImpl <em>Interfaz</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.InterfazImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getInterfaz()
   * @generated
   */
  int INTERFAZ = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFAZ__NAME = ENTIDAD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Propiedades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFAZ__PROPIEDADES = ENTIDAD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Interfaz</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFAZ_FEATURE_COUNT = ENTIDAD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.PropiedadImpl <em>Propiedad</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.PropiedadImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getPropiedad()
   * @generated
   */
  int PROPIEDAD = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPIEDAD__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo Dato</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPIEDAD__TIPO_DATO = 1;

  /**
   * The number of structural features of the '<em>Propiedad</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPIEDAD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl <em>Componente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.ComponenteImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getComponente()
   * @generated
   */
  int COMPONENTE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Interfaz</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__INTERFAZ = 1;

  /**
   * The feature id for the '<em><b>Servicio</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__SERVICIO = 2;

  /**
   * The feature id for the '<em><b>Tecnologia</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__TECNOLOGIA = 3;

  /**
   * The feature id for the '<em><b>Titulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__TITULO = 4;

  /**
   * The feature id for the '<em><b>Campos Entradas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__CAMPOS_ENTRADAS = 5;

  /**
   * The feature id for the '<em><b>Botones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__BOTONES = 6;

  /**
   * The feature id for the '<em><b>Botones Opcion Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__BOTONES_OPCION_ITEM = 7;

  /**
   * The feature id for the '<em><b>Metodos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__METODOS = 8;

  /**
   * The feature id for the '<em><b>Arreglos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__ARREGLOS = 9;

  /**
   * The feature id for the '<em><b>Listado</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__LISTADO = 10;

  /**
   * The feature id for the '<em><b>Lista</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__LISTA = 11;

  /**
   * The number of structural features of the '<em>Componente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE_FEATURE_COUNT = 12;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.CampoEntradaImpl <em>Campo Entrada</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.CampoEntradaImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getCampoEntrada()
   * @generated
   */
  int CAMPO_ENTRADA = 12;

  /**
   * The feature id for the '<em><b>Contenido</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO_ENTRADA__CONTENIDO = 0;

  /**
   * The feature id for the '<em><b>Modelo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO_ENTRADA__MODELO = 1;

  /**
   * The feature id for the '<em><b>Campo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO_ENTRADA__CAMPO = 2;

  /**
   * The number of structural features of the '<em>Campo Entrada</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO_ENTRADA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.BotonImpl <em>Boton</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.BotonImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getBoton()
   * @generated
   */
  int BOTON = 13;

  /**
   * The feature id for the '<em><b>Contenido</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON__CONTENIDO = 0;

  /**
   * The feature id for the '<em><b>Evento</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON__EVENTO = 1;

  /**
   * The feature id for the '<em><b>Metodo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON__METODO = 2;

  /**
   * The number of structural features of the '<em>Boton</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.BotonOpcionItemImpl <em>Boton Opcion Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.BotonOpcionItemImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getBotonOpcionItem()
   * @generated
   */
  int BOTON_OPCION_ITEM = 14;

  /**
   * The feature id for the '<em><b>Contenido</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON_OPCION_ITEM__CONTENIDO = 0;

  /**
   * The feature id for the '<em><b>Evento</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON_OPCION_ITEM__EVENTO = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON_OPCION_ITEM__COLOR = 2;

  /**
   * The feature id for the '<em><b>Metodo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON_OPCION_ITEM__METODO = 3;

  /**
   * The number of structural features of the '<em>Boton Opcion Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTON_OPCION_ITEM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.ListaImpl <em>Lista</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.ListaImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getLista()
   * @generated
   */
  int LISTA = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA__NAME = 0;

  /**
   * The feature id for the '<em><b>Contenido</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA__CONTENIDO = 1;

  /**
   * The number of structural features of the '<em>Lista</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.TiposImpl <em>Tipos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.TiposImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTipos()
   * @generated
   */
  int TIPOS = 16;

  /**
   * The feature id for the '<em><b>Tipo Primitivo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPOS__TIPO_PRIMITIVO = 0;

  /**
   * The feature id for the '<em><b>Tipo Estructurado</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPOS__TIPO_ESTRUCTURADO = 1;

  /**
   * The number of structural features of the '<em>Tipos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPOS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.LLaveImpl <em>LLave</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.LLaveImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getLLave()
   * @generated
   */
  int LLAVE = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE__NAME = 0;

  /**
   * The number of structural features of the '<em>LLave</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.TiposArregloListadoImpl <em>Tipos Arreglo Listado</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.TiposArregloListadoImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTiposArregloListado()
   * @generated
   */
  int TIPOS_ARREGLO_LISTADO = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPOS_ARREGLO_LISTADO__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPOS_ARREGLO_LISTADO__TIPO = 1;

  /**
   * The number of structural features of the '<em>Tipos Arreglo Listado</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPOS_ARREGLO_LISTADO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.ArregloImpl <em>Arreglo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.ArregloImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getArreglo()
   * @generated
   */
  int ARREGLO = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARREGLO__NAME = TIPOS_ARREGLO_LISTADO__NAME;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARREGLO__TIPO = TIPOS_ARREGLO_LISTADO__TIPO;

  /**
   * The number of structural features of the '<em>Arreglo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARREGLO_FEATURE_COUNT = TIPOS_ARREGLO_LISTADO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.impl.ListadoImpl <em>Listado</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.impl.ListadoImpl
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getListado()
   * @generated
   */
  int LISTADO = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTADO__NAME = TIPOS_ARREGLO_LISTADO__NAME;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTADO__TIPO = TIPOS_ARREGLO_LISTADO__TIPO;

  /**
   * The number of structural features of the '<em>Listado</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTADO_FEATURE_COUNT = TIPOS_ARREGLO_LISTADO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.Evento <em>Evento</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.Evento
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getEvento()
   * @generated
   */
  int EVENTO = 21;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.TipoDato <em>Tipo Dato</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.TipoDato
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTipoDato()
   * @generated
   */
  int TIPO_DATO = 22;

  /**
   * The meta object id for the '{@link co.edu.unal.dsl.appPrecio.Color <em>Color</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.unal.dsl.appPrecio.Color
   * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getColor()
   * @generated
   */
  int COLOR = 23;


  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.AppPrecio <em>App Precio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>App Precio</em>'.
   * @see co.edu.unal.dsl.appPrecio.AppPrecio
   * @generated
   */
  EClass getAppPrecio();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.unal.dsl.appPrecio.AppPrecio#getDominio <em>Dominio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dominio</em>'.
   * @see co.edu.unal.dsl.appPrecio.AppPrecio#getDominio()
   * @see #getAppPrecio()
   * @generated
   */
  EReference getAppPrecio_Dominio();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.unal.dsl.appPrecio.AppPrecio#getArquitectura <em>Arquitectura</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arquitectura</em>'.
   * @see co.edu.unal.dsl.appPrecio.AppPrecio#getArquitectura()
   * @see #getAppPrecio()
   * @generated
   */
  EReference getAppPrecio_Arquitectura();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.unal.dsl.appPrecio.AppPrecio#getTecnologia <em>Tecnologia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tecnologia</em>'.
   * @see co.edu.unal.dsl.appPrecio.AppPrecio#getTecnologia()
   * @see #getAppPrecio()
   * @generated
   */
  EReference getAppPrecio_Tecnologia();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Dominio <em>Dominio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dominio</em>'.
   * @see co.edu.unal.dsl.appPrecio.Dominio
   * @generated
   */
  EClass getDominio();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Dominio#getServicios <em>Servicios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servicios</em>'.
   * @see co.edu.unal.dsl.appPrecio.Dominio#getServicios()
   * @see #getDominio()
   * @generated
   */
  EReference getDominio_Servicios();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Dominio#getEntidades <em>Entidades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entidades</em>'.
   * @see co.edu.unal.dsl.appPrecio.Dominio#getEntidades()
   * @see #getDominio()
   * @generated
   */
  EReference getDominio_Entidades();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Arquitectura <em>Arquitectura</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arquitectura</em>'.
   * @see co.edu.unal.dsl.appPrecio.Arquitectura
   * @generated
   */
  EClass getArquitectura();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Arquitectura#getComponentes <em>Componentes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Componentes</em>'.
   * @see co.edu.unal.dsl.appPrecio.Arquitectura#getComponentes()
   * @see #getArquitectura()
   * @generated
   */
  EReference getArquitectura_Componentes();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Tecnologia <em>Tecnologia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tecnologia</em>'.
   * @see co.edu.unal.dsl.appPrecio.Tecnologia
   * @generated
   */
  EClass getTecnologia();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Tecnologia#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.Tecnologia#getName()
   * @see #getTecnologia()
   * @generated
   */
  EAttribute getTecnologia_Name();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.unal.dsl.appPrecio.Tecnologia#getLlave <em>Llave</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Llave</em>'.
   * @see co.edu.unal.dsl.appPrecio.Tecnologia#getLlave()
   * @see #getTecnologia()
   * @generated
   */
  EReference getTecnologia_Llave();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Tecnologia#getMetodos <em>Metodos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metodos</em>'.
   * @see co.edu.unal.dsl.appPrecio.Tecnologia#getMetodos()
   * @see #getTecnologia()
   * @generated
   */
  EReference getTecnologia_Metodos();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Servicio <em>Servicio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Servicio</em>'.
   * @see co.edu.unal.dsl.appPrecio.Servicio
   * @generated
   */
  EClass getServicio();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Servicio#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.Servicio#getName()
   * @see #getServicio()
   * @generated
   */
  EAttribute getServicio_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Servicio#getMetodos <em>Metodos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metodos</em>'.
   * @see co.edu.unal.dsl.appPrecio.Servicio#getMetodos()
   * @see #getServicio()
   * @generated
   */
  EReference getServicio_Metodos();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.MetodoComponente <em>Metodo Componente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metodo Componente</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoComponente
   * @generated
   */
  EClass getMetodoComponente();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.MetodoComponente#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoComponente#getName()
   * @see #getMetodoComponente()
   * @generated
   */
  EAttribute getMetodoComponente_Name();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.MetodoComponente#getMetodoServicio <em>Metodo Servicio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Metodo Servicio</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoComponente#getMetodoServicio()
   * @see #getMetodoComponente()
   * @generated
   */
  EReference getMetodoComponente_MetodoServicio();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.MetodoComponente#getMensaje <em>Mensaje</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mensaje</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoComponente#getMensaje()
   * @see #getMetodoComponente()
   * @generated
   */
  EAttribute getMetodoComponente_Mensaje();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.MetodoServicio <em>Metodo Servicio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metodo Servicio</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoServicio
   * @generated
   */
  EClass getMetodoServicio();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoServicio#getName()
   * @see #getMetodoServicio()
   * @generated
   */
  EAttribute getMetodoServicio_Name();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoParametro <em>Tipo Parametro</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Parametro</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoParametro()
   * @see #getMetodoServicio()
   * @generated
   */
  EReference getMetodoServicio_TipoParametro();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoRetorno <em>Tipo Retorno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Retorno</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoRetorno()
   * @see #getMetodoServicio()
   * @generated
   */
  EReference getMetodoServicio_TipoRetorno();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.MetodoTecnologia <em>Metodo Tecnologia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metodo Tecnologia</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoTecnologia
   * @generated
   */
  EClass getMetodoTecnologia();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.MetodoTecnologia#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoTecnologia#getName()
   * @see #getMetodoTecnologia()
   * @generated
   */
  EAttribute getMetodoTecnologia_Name();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.MetodoTecnologia#getLlave <em>Llave</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Llave</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoTecnologia#getLlave()
   * @see #getMetodoTecnologia()
   * @generated
   */
  EReference getMetodoTecnologia_Llave();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.MetodoTecnologia#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Valor</em>'.
   * @see co.edu.unal.dsl.appPrecio.MetodoTecnologia#getValor()
   * @see #getMetodoTecnologia()
   * @generated
   */
  EReference getMetodoTecnologia_Valor();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Entidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad</em>'.
   * @see co.edu.unal.dsl.appPrecio.Entidad
   * @generated
   */
  EClass getEntidad();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Interfaz <em>Interfaz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interfaz</em>'.
   * @see co.edu.unal.dsl.appPrecio.Interfaz
   * @generated
   */
  EClass getInterfaz();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Interfaz#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.Interfaz#getName()
   * @see #getInterfaz()
   * @generated
   */
  EAttribute getInterfaz_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Interfaz#getPropiedades <em>Propiedades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Propiedades</em>'.
   * @see co.edu.unal.dsl.appPrecio.Interfaz#getPropiedades()
   * @see #getInterfaz()
   * @generated
   */
  EReference getInterfaz_Propiedades();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Propiedad <em>Propiedad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Propiedad</em>'.
   * @see co.edu.unal.dsl.appPrecio.Propiedad
   * @generated
   */
  EClass getPropiedad();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Propiedad#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.Propiedad#getName()
   * @see #getPropiedad()
   * @generated
   */
  EAttribute getPropiedad_Name();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Propiedad#getTipoDato <em>Tipo Dato</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Dato</em>'.
   * @see co.edu.unal.dsl.appPrecio.Propiedad#getTipoDato()
   * @see #getPropiedad()
   * @generated
   */
  EAttribute getPropiedad_TipoDato();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Componente <em>Componente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Componente</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente
   * @generated
   */
  EClass getComponente();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Componente#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getName()
   * @see #getComponente()
   * @generated
   */
  EAttribute getComponente_Name();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.Componente#getInterfaz <em>Interfaz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Interfaz</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getInterfaz()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Interfaz();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.Componente#getServicio <em>Servicio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Servicio</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getServicio()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Servicio();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.Componente#getTecnologia <em>Tecnologia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tecnologia</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getTecnologia()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Tecnologia();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Componente#getTitulo <em>Titulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Titulo</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getTitulo()
   * @see #getComponente()
   * @generated
   */
  EAttribute getComponente_Titulo();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Componente#getCamposEntradas <em>Campos Entradas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Campos Entradas</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getCamposEntradas()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_CamposEntradas();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Componente#getBotones <em>Botones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Botones</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getBotones()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Botones();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Componente#getBotonesOpcionItem <em>Botones Opcion Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Botones Opcion Item</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getBotonesOpcionItem()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_BotonesOpcionItem();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Componente#getMetodos <em>Metodos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metodos</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getMetodos()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Metodos();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Componente#getArreglos <em>Arreglos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arreglos</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getArreglos()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Arreglos();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.unal.dsl.appPrecio.Componente#getListado <em>Listado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Listado</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getListado()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Listado();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.unal.dsl.appPrecio.Componente#getLista <em>Lista</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lista</em>'.
   * @see co.edu.unal.dsl.appPrecio.Componente#getLista()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Lista();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.CampoEntrada <em>Campo Entrada</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Campo Entrada</em>'.
   * @see co.edu.unal.dsl.appPrecio.CampoEntrada
   * @generated
   */
  EClass getCampoEntrada();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.CampoEntrada#getContenido <em>Contenido</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contenido</em>'.
   * @see co.edu.unal.dsl.appPrecio.CampoEntrada#getContenido()
   * @see #getCampoEntrada()
   * @generated
   */
  EAttribute getCampoEntrada_Contenido();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.CampoEntrada#getModelo <em>Modelo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Modelo</em>'.
   * @see co.edu.unal.dsl.appPrecio.CampoEntrada#getModelo()
   * @see #getCampoEntrada()
   * @generated
   */
  EReference getCampoEntrada_Modelo();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.CampoEntrada#getCampo <em>Campo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Campo</em>'.
   * @see co.edu.unal.dsl.appPrecio.CampoEntrada#getCampo()
   * @see #getCampoEntrada()
   * @generated
   */
  EReference getCampoEntrada_Campo();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Boton <em>Boton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boton</em>'.
   * @see co.edu.unal.dsl.appPrecio.Boton
   * @generated
   */
  EClass getBoton();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Boton#getContenido <em>Contenido</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contenido</em>'.
   * @see co.edu.unal.dsl.appPrecio.Boton#getContenido()
   * @see #getBoton()
   * @generated
   */
  EAttribute getBoton_Contenido();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Boton#getEvento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Evento</em>'.
   * @see co.edu.unal.dsl.appPrecio.Boton#getEvento()
   * @see #getBoton()
   * @generated
   */
  EAttribute getBoton_Evento();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.Boton#getMetodo <em>Metodo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Metodo</em>'.
   * @see co.edu.unal.dsl.appPrecio.Boton#getMetodo()
   * @see #getBoton()
   * @generated
   */
  EReference getBoton_Metodo();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem <em>Boton Opcion Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boton Opcion Item</em>'.
   * @see co.edu.unal.dsl.appPrecio.BotonOpcionItem
   * @generated
   */
  EClass getBotonOpcionItem();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getContenido <em>Contenido</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contenido</em>'.
   * @see co.edu.unal.dsl.appPrecio.BotonOpcionItem#getContenido()
   * @see #getBotonOpcionItem()
   * @generated
   */
  EAttribute getBotonOpcionItem_Contenido();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getEvento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Evento</em>'.
   * @see co.edu.unal.dsl.appPrecio.BotonOpcionItem#getEvento()
   * @see #getBotonOpcionItem()
   * @generated
   */
  EAttribute getBotonOpcionItem_Evento();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see co.edu.unal.dsl.appPrecio.BotonOpcionItem#getColor()
   * @see #getBotonOpcionItem()
   * @generated
   */
  EAttribute getBotonOpcionItem_Color();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getMetodo <em>Metodo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Metodo</em>'.
   * @see co.edu.unal.dsl.appPrecio.BotonOpcionItem#getMetodo()
   * @see #getBotonOpcionItem()
   * @generated
   */
  EReference getBotonOpcionItem_Metodo();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Lista <em>Lista</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lista</em>'.
   * @see co.edu.unal.dsl.appPrecio.Lista
   * @generated
   */
  EClass getLista();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Lista#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.Lista#getName()
   * @see #getLista()
   * @generated
   */
  EAttribute getLista_Name();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Lista#getContenido <em>Contenido</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contenido</em>'.
   * @see co.edu.unal.dsl.appPrecio.Lista#getContenido()
   * @see #getLista()
   * @generated
   */
  EAttribute getLista_Contenido();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Tipos <em>Tipos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipos</em>'.
   * @see co.edu.unal.dsl.appPrecio.Tipos
   * @generated
   */
  EClass getTipos();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.Tipos#getTipoPrimitivo <em>Tipo Primitivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Primitivo</em>'.
   * @see co.edu.unal.dsl.appPrecio.Tipos#getTipoPrimitivo()
   * @see #getTipos()
   * @generated
   */
  EAttribute getTipos_TipoPrimitivo();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.Tipos#getTipoEstructurado <em>Tipo Estructurado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tipo Estructurado</em>'.
   * @see co.edu.unal.dsl.appPrecio.Tipos#getTipoEstructurado()
   * @see #getTipos()
   * @generated
   */
  EReference getTipos_TipoEstructurado();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.LLave <em>LLave</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LLave</em>'.
   * @see co.edu.unal.dsl.appPrecio.LLave
   * @generated
   */
  EClass getLLave();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.LLave#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.LLave#getName()
   * @see #getLLave()
   * @generated
   */
  EAttribute getLLave_Name();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Arreglo <em>Arreglo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arreglo</em>'.
   * @see co.edu.unal.dsl.appPrecio.Arreglo
   * @generated
   */
  EClass getArreglo();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.Listado <em>Listado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Listado</em>'.
   * @see co.edu.unal.dsl.appPrecio.Listado
   * @generated
   */
  EClass getListado();

  /**
   * Returns the meta object for class '{@link co.edu.unal.dsl.appPrecio.TiposArregloListado <em>Tipos Arreglo Listado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipos Arreglo Listado</em>'.
   * @see co.edu.unal.dsl.appPrecio.TiposArregloListado
   * @generated
   */
  EClass getTiposArregloListado();

  /**
   * Returns the meta object for the attribute '{@link co.edu.unal.dsl.appPrecio.TiposArregloListado#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.unal.dsl.appPrecio.TiposArregloListado#getName()
   * @see #getTiposArregloListado()
   * @generated
   */
  EAttribute getTiposArregloListado_Name();

  /**
   * Returns the meta object for the reference '{@link co.edu.unal.dsl.appPrecio.TiposArregloListado#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tipo</em>'.
   * @see co.edu.unal.dsl.appPrecio.TiposArregloListado#getTipo()
   * @see #getTiposArregloListado()
   * @generated
   */
  EReference getTiposArregloListado_Tipo();

  /**
   * Returns the meta object for enum '{@link co.edu.unal.dsl.appPrecio.Evento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Evento</em>'.
   * @see co.edu.unal.dsl.appPrecio.Evento
   * @generated
   */
  EEnum getEvento();

  /**
   * Returns the meta object for enum '{@link co.edu.unal.dsl.appPrecio.TipoDato <em>Tipo Dato</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Tipo Dato</em>'.
   * @see co.edu.unal.dsl.appPrecio.TipoDato
   * @generated
   */
  EEnum getTipoDato();

  /**
   * Returns the meta object for enum '{@link co.edu.unal.dsl.appPrecio.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color</em>'.
   * @see co.edu.unal.dsl.appPrecio.Color
   * @generated
   */
  EEnum getColor();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AppPrecioFactory getAppPrecioFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.AppPrecioImpl <em>App Precio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getAppPrecio()
     * @generated
     */
    EClass APP_PRECIO = eINSTANCE.getAppPrecio();

    /**
     * The meta object literal for the '<em><b>Dominio</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APP_PRECIO__DOMINIO = eINSTANCE.getAppPrecio_Dominio();

    /**
     * The meta object literal for the '<em><b>Arquitectura</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APP_PRECIO__ARQUITECTURA = eINSTANCE.getAppPrecio_Arquitectura();

    /**
     * The meta object literal for the '<em><b>Tecnologia</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APP_PRECIO__TECNOLOGIA = eINSTANCE.getAppPrecio_Tecnologia();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.DominioImpl <em>Dominio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.DominioImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getDominio()
     * @generated
     */
    EClass DOMINIO = eINSTANCE.getDominio();

    /**
     * The meta object literal for the '<em><b>Servicios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMINIO__SERVICIOS = eINSTANCE.getDominio_Servicios();

    /**
     * The meta object literal for the '<em><b>Entidades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMINIO__ENTIDADES = eINSTANCE.getDominio_Entidades();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.ArquitecturaImpl <em>Arquitectura</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.ArquitecturaImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getArquitectura()
     * @generated
     */
    EClass ARQUITECTURA = eINSTANCE.getArquitectura();

    /**
     * The meta object literal for the '<em><b>Componentes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARQUITECTURA__COMPONENTES = eINSTANCE.getArquitectura_Componentes();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.TecnologiaImpl <em>Tecnologia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.TecnologiaImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTecnologia()
     * @generated
     */
    EClass TECNOLOGIA = eINSTANCE.getTecnologia();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TECNOLOGIA__NAME = eINSTANCE.getTecnologia_Name();

    /**
     * The meta object literal for the '<em><b>Llave</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TECNOLOGIA__LLAVE = eINSTANCE.getTecnologia_Llave();

    /**
     * The meta object literal for the '<em><b>Metodos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TECNOLOGIA__METODOS = eINSTANCE.getTecnologia_Metodos();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.ServicioImpl <em>Servicio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.ServicioImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getServicio()
     * @generated
     */
    EClass SERVICIO = eINSTANCE.getServicio();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICIO__NAME = eINSTANCE.getServicio_Name();

    /**
     * The meta object literal for the '<em><b>Metodos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICIO__METODOS = eINSTANCE.getServicio_Metodos();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.MetodoComponenteImpl <em>Metodo Componente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.MetodoComponenteImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getMetodoComponente()
     * @generated
     */
    EClass METODO_COMPONENTE = eINSTANCE.getMetodoComponente();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METODO_COMPONENTE__NAME = eINSTANCE.getMetodoComponente_Name();

    /**
     * The meta object literal for the '<em><b>Metodo Servicio</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METODO_COMPONENTE__METODO_SERVICIO = eINSTANCE.getMetodoComponente_MetodoServicio();

    /**
     * The meta object literal for the '<em><b>Mensaje</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METODO_COMPONENTE__MENSAJE = eINSTANCE.getMetodoComponente_Mensaje();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.MetodoServicioImpl <em>Metodo Servicio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.MetodoServicioImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getMetodoServicio()
     * @generated
     */
    EClass METODO_SERVICIO = eINSTANCE.getMetodoServicio();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METODO_SERVICIO__NAME = eINSTANCE.getMetodoServicio_Name();

    /**
     * The meta object literal for the '<em><b>Tipo Parametro</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METODO_SERVICIO__TIPO_PARAMETRO = eINSTANCE.getMetodoServicio_TipoParametro();

    /**
     * The meta object literal for the '<em><b>Tipo Retorno</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METODO_SERVICIO__TIPO_RETORNO = eINSTANCE.getMetodoServicio_TipoRetorno();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.MetodoTecnologiaImpl <em>Metodo Tecnologia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.MetodoTecnologiaImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getMetodoTecnologia()
     * @generated
     */
    EClass METODO_TECNOLOGIA = eINSTANCE.getMetodoTecnologia();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METODO_TECNOLOGIA__NAME = eINSTANCE.getMetodoTecnologia_Name();

    /**
     * The meta object literal for the '<em><b>Llave</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METODO_TECNOLOGIA__LLAVE = eINSTANCE.getMetodoTecnologia_Llave();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METODO_TECNOLOGIA__VALOR = eINSTANCE.getMetodoTecnologia_Valor();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.EntidadImpl <em>Entidad</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.EntidadImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getEntidad()
     * @generated
     */
    EClass ENTIDAD = eINSTANCE.getEntidad();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.InterfazImpl <em>Interfaz</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.InterfazImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getInterfaz()
     * @generated
     */
    EClass INTERFAZ = eINSTANCE.getInterfaz();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERFAZ__NAME = eINSTANCE.getInterfaz_Name();

    /**
     * The meta object literal for the '<em><b>Propiedades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFAZ__PROPIEDADES = eINSTANCE.getInterfaz_Propiedades();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.PropiedadImpl <em>Propiedad</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.PropiedadImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getPropiedad()
     * @generated
     */
    EClass PROPIEDAD = eINSTANCE.getPropiedad();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPIEDAD__NAME = eINSTANCE.getPropiedad_Name();

    /**
     * The meta object literal for the '<em><b>Tipo Dato</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPIEDAD__TIPO_DATO = eINSTANCE.getPropiedad_TipoDato();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.ComponenteImpl <em>Componente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.ComponenteImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getComponente()
     * @generated
     */
    EClass COMPONENTE = eINSTANCE.getComponente();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENTE__NAME = eINSTANCE.getComponente_Name();

    /**
     * The meta object literal for the '<em><b>Interfaz</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__INTERFAZ = eINSTANCE.getComponente_Interfaz();

    /**
     * The meta object literal for the '<em><b>Servicio</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__SERVICIO = eINSTANCE.getComponente_Servicio();

    /**
     * The meta object literal for the '<em><b>Tecnologia</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__TECNOLOGIA = eINSTANCE.getComponente_Tecnologia();

    /**
     * The meta object literal for the '<em><b>Titulo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENTE__TITULO = eINSTANCE.getComponente_Titulo();

    /**
     * The meta object literal for the '<em><b>Campos Entradas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__CAMPOS_ENTRADAS = eINSTANCE.getComponente_CamposEntradas();

    /**
     * The meta object literal for the '<em><b>Botones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__BOTONES = eINSTANCE.getComponente_Botones();

    /**
     * The meta object literal for the '<em><b>Botones Opcion Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__BOTONES_OPCION_ITEM = eINSTANCE.getComponente_BotonesOpcionItem();

    /**
     * The meta object literal for the '<em><b>Metodos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__METODOS = eINSTANCE.getComponente_Metodos();

    /**
     * The meta object literal for the '<em><b>Arreglos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__ARREGLOS = eINSTANCE.getComponente_Arreglos();

    /**
     * The meta object literal for the '<em><b>Listado</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__LISTADO = eINSTANCE.getComponente_Listado();

    /**
     * The meta object literal for the '<em><b>Lista</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__LISTA = eINSTANCE.getComponente_Lista();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.CampoEntradaImpl <em>Campo Entrada</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.CampoEntradaImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getCampoEntrada()
     * @generated
     */
    EClass CAMPO_ENTRADA = eINSTANCE.getCampoEntrada();

    /**
     * The meta object literal for the '<em><b>Contenido</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMPO_ENTRADA__CONTENIDO = eINSTANCE.getCampoEntrada_Contenido();

    /**
     * The meta object literal for the '<em><b>Modelo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMPO_ENTRADA__MODELO = eINSTANCE.getCampoEntrada_Modelo();

    /**
     * The meta object literal for the '<em><b>Campo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMPO_ENTRADA__CAMPO = eINSTANCE.getCampoEntrada_Campo();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.BotonImpl <em>Boton</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.BotonImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getBoton()
     * @generated
     */
    EClass BOTON = eINSTANCE.getBoton();

    /**
     * The meta object literal for the '<em><b>Contenido</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOTON__CONTENIDO = eINSTANCE.getBoton_Contenido();

    /**
     * The meta object literal for the '<em><b>Evento</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOTON__EVENTO = eINSTANCE.getBoton_Evento();

    /**
     * The meta object literal for the '<em><b>Metodo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOTON__METODO = eINSTANCE.getBoton_Metodo();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.BotonOpcionItemImpl <em>Boton Opcion Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.BotonOpcionItemImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getBotonOpcionItem()
     * @generated
     */
    EClass BOTON_OPCION_ITEM = eINSTANCE.getBotonOpcionItem();

    /**
     * The meta object literal for the '<em><b>Contenido</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOTON_OPCION_ITEM__CONTENIDO = eINSTANCE.getBotonOpcionItem_Contenido();

    /**
     * The meta object literal for the '<em><b>Evento</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOTON_OPCION_ITEM__EVENTO = eINSTANCE.getBotonOpcionItem_Evento();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOTON_OPCION_ITEM__COLOR = eINSTANCE.getBotonOpcionItem_Color();

    /**
     * The meta object literal for the '<em><b>Metodo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOTON_OPCION_ITEM__METODO = eINSTANCE.getBotonOpcionItem_Metodo();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.ListaImpl <em>Lista</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.ListaImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getLista()
     * @generated
     */
    EClass LISTA = eINSTANCE.getLista();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LISTA__NAME = eINSTANCE.getLista_Name();

    /**
     * The meta object literal for the '<em><b>Contenido</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LISTA__CONTENIDO = eINSTANCE.getLista_Contenido();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.TiposImpl <em>Tipos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.TiposImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTipos()
     * @generated
     */
    EClass TIPOS = eINSTANCE.getTipos();

    /**
     * The meta object literal for the '<em><b>Tipo Primitivo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPOS__TIPO_PRIMITIVO = eINSTANCE.getTipos_TipoPrimitivo();

    /**
     * The meta object literal for the '<em><b>Tipo Estructurado</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIPOS__TIPO_ESTRUCTURADO = eINSTANCE.getTipos_TipoEstructurado();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.LLaveImpl <em>LLave</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.LLaveImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getLLave()
     * @generated
     */
    EClass LLAVE = eINSTANCE.getLLave();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LLAVE__NAME = eINSTANCE.getLLave_Name();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.ArregloImpl <em>Arreglo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.ArregloImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getArreglo()
     * @generated
     */
    EClass ARREGLO = eINSTANCE.getArreglo();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.ListadoImpl <em>Listado</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.ListadoImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getListado()
     * @generated
     */
    EClass LISTADO = eINSTANCE.getListado();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.impl.TiposArregloListadoImpl <em>Tipos Arreglo Listado</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.impl.TiposArregloListadoImpl
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTiposArregloListado()
     * @generated
     */
    EClass TIPOS_ARREGLO_LISTADO = eINSTANCE.getTiposArregloListado();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPOS_ARREGLO_LISTADO__NAME = eINSTANCE.getTiposArregloListado_Name();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIPOS_ARREGLO_LISTADO__TIPO = eINSTANCE.getTiposArregloListado_Tipo();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.Evento <em>Evento</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.Evento
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getEvento()
     * @generated
     */
    EEnum EVENTO = eINSTANCE.getEvento();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.TipoDato <em>Tipo Dato</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.TipoDato
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getTipoDato()
     * @generated
     */
    EEnum TIPO_DATO = eINSTANCE.getTipoDato();

    /**
     * The meta object literal for the '{@link co.edu.unal.dsl.appPrecio.Color <em>Color</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.unal.dsl.appPrecio.Color
     * @see co.edu.unal.dsl.appPrecio.impl.AppPrecioPackageImpl#getColor()
     * @generated
     */
    EEnum COLOR = eINSTANCE.getColor();

  }

} //AppPrecioPackage
