/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage
 * @generated
 */
public interface AppPrecioFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AppPrecioFactory eINSTANCE = co.edu.unal.dsl.appPrecio.impl.AppPrecioFactoryImpl.init();

  /**
   * Returns a new object of class '<em>App Precio</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>App Precio</em>'.
   * @generated
   */
  AppPrecio createAppPrecio();

  /**
   * Returns a new object of class '<em>Dominio</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dominio</em>'.
   * @generated
   */
  Dominio createDominio();

  /**
   * Returns a new object of class '<em>Arquitectura</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arquitectura</em>'.
   * @generated
   */
  Arquitectura createArquitectura();

  /**
   * Returns a new object of class '<em>Tecnologia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tecnologia</em>'.
   * @generated
   */
  Tecnologia createTecnologia();

  /**
   * Returns a new object of class '<em>Servicio</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Servicio</em>'.
   * @generated
   */
  Servicio createServicio();

  /**
   * Returns a new object of class '<em>Metodo Componente</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metodo Componente</em>'.
   * @generated
   */
  MetodoComponente createMetodoComponente();

  /**
   * Returns a new object of class '<em>Metodo Servicio</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metodo Servicio</em>'.
   * @generated
   */
  MetodoServicio createMetodoServicio();

  /**
   * Returns a new object of class '<em>Metodo Tecnologia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metodo Tecnologia</em>'.
   * @generated
   */
  MetodoTecnologia createMetodoTecnologia();

  /**
   * Returns a new object of class '<em>Entidad</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entidad</em>'.
   * @generated
   */
  Entidad createEntidad();

  /**
   * Returns a new object of class '<em>Interfaz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interfaz</em>'.
   * @generated
   */
  Interfaz createInterfaz();

  /**
   * Returns a new object of class '<em>Propiedad</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propiedad</em>'.
   * @generated
   */
  Propiedad createPropiedad();

  /**
   * Returns a new object of class '<em>Componente</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Componente</em>'.
   * @generated
   */
  Componente createComponente();

  /**
   * Returns a new object of class '<em>Campo Entrada</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Campo Entrada</em>'.
   * @generated
   */
  CampoEntrada createCampoEntrada();

  /**
   * Returns a new object of class '<em>Boton</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boton</em>'.
   * @generated
   */
  Boton createBoton();

  /**
   * Returns a new object of class '<em>Boton Opcion Item</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boton Opcion Item</em>'.
   * @generated
   */
  BotonOpcionItem createBotonOpcionItem();

  /**
   * Returns a new object of class '<em>Lista</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lista</em>'.
   * @generated
   */
  Lista createLista();

  /**
   * Returns a new object of class '<em>Tipos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tipos</em>'.
   * @generated
   */
  Tipos createTipos();

  /**
   * Returns a new object of class '<em>LLave</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LLave</em>'.
   * @generated
   */
  LLave createLLave();

  /**
   * Returns a new object of class '<em>Arreglo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arreglo</em>'.
   * @generated
   */
  Arreglo createArreglo();

  /**
   * Returns a new object of class '<em>Listado</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Listado</em>'.
   * @generated
   */
  Listado createListado();

  /**
   * Returns a new object of class '<em>Tipos Arreglo Listado</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tipos Arreglo Listado</em>'.
   * @generated
   */
  TiposArregloListado createTiposArregloListado();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AppPrecioPackage getAppPrecioPackage();

} //AppPrecioFactory
