/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>App Precio</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.AppPrecio#getDominio <em>Dominio</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.AppPrecio#getArquitectura <em>Arquitectura</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.AppPrecio#getTecnologia <em>Tecnologia</em>}</li>
 * </ul>
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getAppPrecio()
 * @model
 * @generated
 */
public interface AppPrecio extends EObject
{
  /**
   * Returns the value of the '<em><b>Dominio</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dominio</em>' containment reference.
   * @see #setDominio(Dominio)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getAppPrecio_Dominio()
   * @model containment="true"
   * @generated
   */
  Dominio getDominio();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.AppPrecio#getDominio <em>Dominio</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dominio</em>' containment reference.
   * @see #getDominio()
   * @generated
   */
  void setDominio(Dominio value);

  /**
   * Returns the value of the '<em><b>Arquitectura</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arquitectura</em>' containment reference.
   * @see #setArquitectura(Arquitectura)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getAppPrecio_Arquitectura()
   * @model containment="true"
   * @generated
   */
  Arquitectura getArquitectura();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.AppPrecio#getArquitectura <em>Arquitectura</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arquitectura</em>' containment reference.
   * @see #getArquitectura()
   * @generated
   */
  void setArquitectura(Arquitectura value);

  /**
   * Returns the value of the '<em><b>Tecnologia</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tecnologia</em>' containment reference.
   * @see #setTecnologia(Tecnologia)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getAppPrecio_Tecnologia()
   * @model containment="true"
   * @generated
   */
  Tecnologia getTecnologia();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.AppPrecio#getTecnologia <em>Tecnologia</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tecnologia</em>' containment reference.
   * @see #getTecnologia()
   * @generated
   */
  void setTecnologia(Tecnologia value);

} // AppPrecio
