/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arquitectura</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Arquitectura#getComponentes <em>Componentes</em>}</li>
 * </ul>
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getArquitectura()
 * @model
 * @generated
 */
public interface Arquitectura extends EObject
{
  /**
   * Returns the value of the '<em><b>Componentes</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.unal.dsl.appPrecio.Componente}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Componentes</em>' containment reference list.
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getArquitectura_Componentes()
   * @model containment="true"
   * @generated
   */
  EList<Componente> getComponentes();

} // Arquitectura
