/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arreglo</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getArreglo()
 * @model
 * @generated
 */
public interface Arreglo extends TiposArregloListado
{
} // Arreglo
