/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boton Opcion Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getContenido <em>Contenido</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getEvento <em>Evento</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getColor <em>Color</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getMetodo <em>Metodo</em>}</li>
 * </ul>
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getBotonOpcionItem()
 * @model
 * @generated
 */
public interface BotonOpcionItem extends EObject
{
  /**
   * Returns the value of the '<em><b>Contenido</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contenido</em>' attribute.
   * @see #setContenido(String)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getBotonOpcionItem_Contenido()
   * @model
   * @generated
   */
  String getContenido();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getContenido <em>Contenido</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contenido</em>' attribute.
   * @see #getContenido()
   * @generated
   */
  void setContenido(String value);

  /**
   * Returns the value of the '<em><b>Evento</b></em>' attribute.
   * The literals are from the enumeration {@link co.edu.unal.dsl.appPrecio.Evento}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evento</em>' attribute.
   * @see co.edu.unal.dsl.appPrecio.Evento
   * @see #setEvento(Evento)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getBotonOpcionItem_Evento()
   * @model
   * @generated
   */
  Evento getEvento();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getEvento <em>Evento</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Evento</em>' attribute.
   * @see co.edu.unal.dsl.appPrecio.Evento
   * @see #getEvento()
   * @generated
   */
  void setEvento(Evento value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link co.edu.unal.dsl.appPrecio.Color}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see co.edu.unal.dsl.appPrecio.Color
   * @see #setColor(Color)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getBotonOpcionItem_Color()
   * @model
   * @generated
   */
  Color getColor();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see co.edu.unal.dsl.appPrecio.Color
   * @see #getColor()
   * @generated
   */
  void setColor(Color value);

  /**
   * Returns the value of the '<em><b>Metodo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metodo</em>' reference.
   * @see #setMetodo(MetodoComponente)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getBotonOpcionItem_Metodo()
   * @model
   * @generated
   */
  MetodoComponente getMetodo();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.BotonOpcionItem#getMetodo <em>Metodo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metodo</em>' reference.
   * @see #getMetodo()
   * @generated
   */
  void setMetodo(MetodoComponente value);

} // BotonOpcionItem
