/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dominio</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Dominio#getServicios <em>Servicios</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Dominio#getEntidades <em>Entidades</em>}</li>
 * </ul>
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getDominio()
 * @model
 * @generated
 */
public interface Dominio extends EObject
{
  /**
   * Returns the value of the '<em><b>Servicios</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.unal.dsl.appPrecio.Servicio}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Servicios</em>' containment reference list.
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getDominio_Servicios()
   * @model containment="true"
   * @generated
   */
  EList<Servicio> getServicios();

  /**
   * Returns the value of the '<em><b>Entidades</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.unal.dsl.appPrecio.Entidad}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entidades</em>' containment reference list.
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getDominio_Entidades()
   * @model containment="true"
   * @generated
   */
  EList<Entidad> getEntidades();

} // Dominio
