/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entidad</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getEntidad()
 * @model
 * @generated
 */
public interface Entidad extends EObject
{
} // Entidad
