/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metodo Servicio</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoParametro <em>Tipo Parametro</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoRetorno <em>Tipo Retorno</em>}</li>
 * </ul>
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getMetodoServicio()
 * @model
 * @generated
 */
public interface MetodoServicio extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getMetodoServicio_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tipo Parametro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Parametro</em>' containment reference.
   * @see #setTipoParametro(Tipos)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getMetodoServicio_TipoParametro()
   * @model containment="true"
   * @generated
   */
  Tipos getTipoParametro();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoParametro <em>Tipo Parametro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Parametro</em>' containment reference.
   * @see #getTipoParametro()
   * @generated
   */
  void setTipoParametro(Tipos value);

  /**
   * Returns the value of the '<em><b>Tipo Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Retorno</em>' containment reference.
   * @see #setTipoRetorno(Tipos)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getMetodoServicio_TipoRetorno()
   * @model containment="true"
   * @generated
   */
  Tipos getTipoRetorno();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.MetodoServicio#getTipoRetorno <em>Tipo Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Retorno</em>' containment reference.
   * @see #getTipoRetorno()
   * @generated
   */
  void setTipoRetorno(Tipos value);

} // MetodoServicio
