/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Propiedad</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Propiedad#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Propiedad#getTipoDato <em>Tipo Dato</em>}</li>
 * </ul>
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getPropiedad()
 * @model
 * @generated
 */
public interface Propiedad extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getPropiedad_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.Propiedad#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tipo Dato</b></em>' attribute.
   * The literals are from the enumeration {@link co.edu.unal.dsl.appPrecio.TipoDato}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Dato</em>' attribute.
   * @see co.edu.unal.dsl.appPrecio.TipoDato
   * @see #setTipoDato(TipoDato)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getPropiedad_TipoDato()
   * @model
   * @generated
   */
  TipoDato getTipoDato();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.Propiedad#getTipoDato <em>Tipo Dato</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Dato</em>' attribute.
   * @see co.edu.unal.dsl.appPrecio.TipoDato
   * @see #getTipoDato()
   * @generated
   */
  void setTipoDato(TipoDato value);

} // Propiedad
