/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tecnologia</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Tecnologia#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Tecnologia#getLlave <em>Llave</em>}</li>
 *   <li>{@link co.edu.unal.dsl.appPrecio.Tecnologia#getMetodos <em>Metodos</em>}</li>
 * </ul>
 *
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getTecnologia()
 * @model
 * @generated
 */
public interface Tecnologia extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getTecnologia_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.Tecnologia#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Llave</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Llave</em>' containment reference.
   * @see #setLlave(LLave)
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getTecnologia_Llave()
   * @model containment="true"
   * @generated
   */
  LLave getLlave();

  /**
   * Sets the value of the '{@link co.edu.unal.dsl.appPrecio.Tecnologia#getLlave <em>Llave</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Llave</em>' containment reference.
   * @see #getLlave()
   * @generated
   */
  void setLlave(LLave value);

  /**
   * Returns the value of the '<em><b>Metodos</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.unal.dsl.appPrecio.MetodoTecnologia}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metodos</em>' containment reference list.
   * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getTecnologia_Metodos()
   * @model containment="true"
   * @generated
   */
  EList<MetodoTecnologia> getMetodos();

} // Tecnologia
