/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Tipo Dato</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage#getTipoDato()
 * @model
 * @generated
 */
public enum TipoDato implements Enumerator
{
  /**
   * The '<em><b>Numero</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NUMERO_VALUE
   * @generated
   * @ordered
   */
  NUMERO(0, "numero", "number"),

  /**
   * The '<em><b>Cadena</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CADENA_VALUE
   * @generated
   * @ordered
   */
  CADENA(1, "cadena", "string"),

  /**
   * The '<em><b>Ninguna</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NINGUNA_VALUE
   * @generated
   * @ordered
   */
  NINGUNA(2, "ninguna", "any");

  /**
   * The '<em><b>Numero</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NUMERO
   * @model name="numero" literal="number"
   * @generated
   * @ordered
   */
  public static final int NUMERO_VALUE = 0;

  /**
   * The '<em><b>Cadena</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CADENA
   * @model name="cadena" literal="string"
   * @generated
   * @ordered
   */
  public static final int CADENA_VALUE = 1;

  /**
   * The '<em><b>Ninguna</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NINGUNA
   * @model name="ninguna" literal="any"
   * @generated
   * @ordered
   */
  public static final int NINGUNA_VALUE = 2;

  /**
   * An array of all the '<em><b>Tipo Dato</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TipoDato[] VALUES_ARRAY =
    new TipoDato[]
    {
      NUMERO,
      CADENA,
      NINGUNA,
    };

  /**
   * A public read-only list of all the '<em><b>Tipo Dato</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TipoDato> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Tipo Dato</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TipoDato get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TipoDato result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Tipo Dato</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TipoDato getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TipoDato result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Tipo Dato</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TipoDato get(int value)
  {
    switch (value)
    {
      case NUMERO_VALUE: return NUMERO;
      case CADENA_VALUE: return CADENA;
      case NINGUNA_VALUE: return NINGUNA;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TipoDato(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TipoDato
