/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.ide;

import co.edu.unal.dsl.ide.AbstractAppPrecioIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AppPrecioIdeModule extends AbstractAppPrecioIdeModule {
}
