/*
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AppPrecioAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co/edu/unal/dsl/parser/antlr/internal/InternalAppPrecio.tokens");
	}
}
