/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.validation;

import co.edu.unal.dsl.validation.AbstractAppPrecioValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AppPrecioValidator extends AbstractAppPrecioValidator {
}
