/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.ui;

import co.edu.unal.dsl.ui.AbstractAppPrecioUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AppPrecioUiModule extends AbstractAppPrecioUiModule {
  public AppPrecioUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
