/*
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.ui;

import co.edu.unal.dsl.AppPrecio.ui.internal.AppPrecioActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AppPrecioExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AppPrecioActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AppPrecioActivator activator = AppPrecioActivator.getInstance();
		return activator != null ? activator.getInjector(AppPrecioActivator.CO_EDU_UNAL_DSL_APPPRECIO) : null;
	}

}
