/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.appPrecio.util;

import co.edu.unal.dsl.appPrecio.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see co.edu.unal.dsl.appPrecio.AppPrecioPackage
 * @generated
 */
public class AppPrecioSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static AppPrecioPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AppPrecioSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = AppPrecioPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case AppPrecioPackage.APP_PRECIO:
      {
        AppPrecio appPrecio = (AppPrecio)theEObject;
        T result = caseAppPrecio(appPrecio);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.DOMINIO:
      {
        Dominio dominio = (Dominio)theEObject;
        T result = caseDominio(dominio);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.ARQUITECTURA:
      {
        Arquitectura arquitectura = (Arquitectura)theEObject;
        T result = caseArquitectura(arquitectura);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.TECNOLOGIA:
      {
        Tecnologia tecnologia = (Tecnologia)theEObject;
        T result = caseTecnologia(tecnologia);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.SERVICIO:
      {
        Servicio servicio = (Servicio)theEObject;
        T result = caseServicio(servicio);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.METODO_COMPONENTE:
      {
        MetodoComponente metodoComponente = (MetodoComponente)theEObject;
        T result = caseMetodoComponente(metodoComponente);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.METODO_SERVICIO:
      {
        MetodoServicio metodoServicio = (MetodoServicio)theEObject;
        T result = caseMetodoServicio(metodoServicio);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.METODO_TECNOLOGIA:
      {
        MetodoTecnologia metodoTecnologia = (MetodoTecnologia)theEObject;
        T result = caseMetodoTecnologia(metodoTecnologia);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.ENTIDAD:
      {
        Entidad entidad = (Entidad)theEObject;
        T result = caseEntidad(entidad);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.INTERFAZ:
      {
        Interfaz interfaz = (Interfaz)theEObject;
        T result = caseInterfaz(interfaz);
        if (result == null) result = caseEntidad(interfaz);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.PROPIEDAD:
      {
        Propiedad propiedad = (Propiedad)theEObject;
        T result = casePropiedad(propiedad);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.COMPONENTE:
      {
        Componente componente = (Componente)theEObject;
        T result = caseComponente(componente);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.CAMPO_ENTRADA:
      {
        CampoEntrada campoEntrada = (CampoEntrada)theEObject;
        T result = caseCampoEntrada(campoEntrada);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.BOTON:
      {
        Boton boton = (Boton)theEObject;
        T result = caseBoton(boton);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.BOTON_OPCION_ITEM:
      {
        BotonOpcionItem botonOpcionItem = (BotonOpcionItem)theEObject;
        T result = caseBotonOpcionItem(botonOpcionItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.LISTA:
      {
        Lista lista = (Lista)theEObject;
        T result = caseLista(lista);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.TIPOS:
      {
        Tipos tipos = (Tipos)theEObject;
        T result = caseTipos(tipos);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.LLAVE:
      {
        LLave lLave = (LLave)theEObject;
        T result = caseLLave(lLave);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.ARREGLO:
      {
        Arreglo arreglo = (Arreglo)theEObject;
        T result = caseArreglo(arreglo);
        if (result == null) result = caseTiposArregloListado(arreglo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.LISTADO:
      {
        Listado listado = (Listado)theEObject;
        T result = caseListado(listado);
        if (result == null) result = caseTiposArregloListado(listado);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AppPrecioPackage.TIPOS_ARREGLO_LISTADO:
      {
        TiposArregloListado tiposArregloListado = (TiposArregloListado)theEObject;
        T result = caseTiposArregloListado(tiposArregloListado);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>App Precio</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>App Precio</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAppPrecio(AppPrecio object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dominio</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dominio</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDominio(Dominio object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Arquitectura</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Arquitectura</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseArquitectura(Arquitectura object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Tecnologia</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Tecnologia</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTecnologia(Tecnologia object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Servicio</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Servicio</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseServicio(Servicio object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Metodo Componente</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Metodo Componente</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMetodoComponente(MetodoComponente object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Metodo Servicio</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Metodo Servicio</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMetodoServicio(MetodoServicio object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Metodo Tecnologia</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Metodo Tecnologia</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMetodoTecnologia(MetodoTecnologia object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Entidad</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Entidad</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEntidad(Entidad object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Interfaz</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Interfaz</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInterfaz(Interfaz object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Propiedad</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Propiedad</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePropiedad(Propiedad object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Componente</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Componente</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComponente(Componente object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Campo Entrada</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Campo Entrada</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCampoEntrada(CampoEntrada object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boton</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boton</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoton(Boton object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boton Opcion Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boton Opcion Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBotonOpcionItem(BotonOpcionItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Lista</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Lista</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLista(Lista object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Tipos</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Tipos</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTipos(Tipos object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>LLave</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>LLave</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLLave(LLave object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Arreglo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Arreglo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseArreglo(Arreglo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Listado</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Listado</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseListado(Listado object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Tipos Arreglo Listado</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Tipos Arreglo Listado</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTiposArregloListado(TiposArregloListado object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //AppPrecioSwitch
