/*
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAppPrecioValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(co.edu.unal.dsl.appPrecio.AppPrecioPackage.eINSTANCE);
		return result;
	}
}
