/**
 * generated by Xtext 2.19.0
 */
package co.edu.unal.dsl;

import co.edu.unal.dsl.AbstractAppPrecioRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AppPrecioRuntimeModule extends AbstractAppPrecioRuntimeModule {
}
